package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUsageRecord;
import org.linlinjava.litemall.db.domain.LitemallUsageRecordExample;
public interface LitemallUsageRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    int countByExample(LitemallUsageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    int deleteByExample(LitemallUsageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    int insert(LitemallUsageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    int insertSelective(LitemallUsageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    List<LitemallUsageRecord> selectByExample(LitemallUsageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    LitemallUsageRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LitemallUsageRecord record, @Param("example") LitemallUsageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LitemallUsageRecord record, @Param("example") LitemallUsageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LitemallUsageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usage_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LitemallUsageRecord record);

    /**
     * 查询订单详细信息(包含柜组区域信息)
     * @param id
     * @return
     */
    LitemallUsageRecord queryUsage(Integer id);
    
}