package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TicAdCategory;
import org.linlinjava.litemall.db.domain.TicAdCategoryExample;
import org.linlinjava.litemall.db.request.TicAdCateRequest;

public interface TicAdCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    int countByExample(TicAdCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    int deleteByExample(TicAdCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    int insert(TicAdCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    int insertSelective(TicAdCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    List<TicAdCategory> selectByExample(TicAdCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    TicAdCategory selectByPrimaryKey(Integer adcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TicAdCategory record, @Param("example") TicAdCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TicAdCategory record, @Param("example") TicAdCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TicAdCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TicAdCategory record);
    /**
     * 条件查询（排序）
     * @param adCateReq
     * @return
     * @author liuyu
     */
    List<TicAdCategory> selectAdCate(TicAdCateRequest adCateReq);
}