package org.linlinjava.litemall.db.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.CustomTicCouAndCos;
import org.linlinjava.litemall.db.domain.TicCouponUser;
import org.linlinjava.litemall.db.domain.TicCouponUserExample;

public interface TicCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    int countByExample(TicCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    int deleteByExample(TicCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cosId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    int insert(TicCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    int insertSelective(TicCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    List<TicCouponUser> selectByExample(TicCouponUserExample TicCouponUserExample);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    TicCouponUser selectByPrimaryKey(Integer cosId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TicCouponUser record, @Param("example") TicCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TicCouponUser record, @Param("example") TicCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TicCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TicCouponUser record);
    
    List<CustomTicCouAndCos> MayUseCoupon(@SuppressWarnings("rawtypes") Map map);

    /**
     * 条件修改（userId,couponId）
     * @param record
     * @return
     */
    int updateSelect(TicCouponUser record);
}