package org.linlinjava.litemall.db.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TicCategory;
import org.linlinjava.litemall.db.domain.TicCategoryExample;
import org.linlinjava.litemall.db.request.TicCateRequest;
import org.linlinjava.litemall.db.response.TicCateResponse;

public interface TicCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    int countByExample(TicCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    int deleteByExample(TicCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    int insert(TicCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    int insertSelective(TicCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    List<TicCategory> selectByExample(TicCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    TicCategory selectByPrimaryKey(Integer catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TicCategory record, @Param("example") TicCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TicCategory record, @Param("example") TicCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TicCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TicCategory record);
    /**
     * 条件查询（排序）
     * @param cateRequest
     * @return
     * @author liuyu
     */
    List<TicCategory> selectCate(TicCateRequest cateRequest);
    
    /**
     * 自主取票机查询门票类目
     * @param map
     * @return
     */
    List<TicCategory> SelfHelpList(@SuppressWarnings("rawtypes") Map map);

    /**
     * 人工窗口门票类目以及门票
     * @return
     * @author liuyu
     */
    List<TicCateResponse> WinGoodList();
}