package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCoupon;
import org.linlinjava.litemall.db.domain.LitemallCouponExample;
import org.linlinjava.litemall.db.domain.TicCoupon;
import org.linlinjava.litemall.db.domain.TicCouponExample;

public interface TicCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    int countByExample(TicCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    int deleteByExample(TicCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer couId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    int insert(TicCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    int insertSelective(TicCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    List<TicCoupon> selectByExample(TicCouponExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TicCoupon> selectByExampleSelective(@Param("example") TicCouponExample example, @Param("selective") TicCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    TicCoupon selectByPrimaryKey(Integer couId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TicCoupon record, @Param("example") TicCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TicCoupon record, @Param("example") TicCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TicCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TicCoupon record);
}