package org.linlinjava.litemall.db.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.OrderGoodsReturn;
import org.linlinjava.litemall.db.domain.TicOrder;
import org.linlinjava.litemall.db.domain.TicOrderGoods;
import org.linlinjava.litemall.db.domain.TicOrderGoodsExample;
import org.linlinjava.litemall.db.request.TicStaticRequest;
import org.linlinjava.litemall.db.response.TicOrderGoodResponse;

public interface TicOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    int countByExample(TicOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    int deleteByExample(TicOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    int insert(TicOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    int insertSelective(TicOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    List<TicOrderGoods> selectByExample(TicOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    TicOrderGoods selectByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TicOrderGoods record, @Param("example") TicOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TicOrderGoods record, @Param("example") TicOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TicOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TicOrderGoods record);

    /**
     * 批量添加
     * @param list
     * @return
     */
    int addBatch(List<TicOrderGoods> list);

    /**
     * 根据订单ID查询购买的门票及数量
     * @param ordId
     * @return
     */
    List<OrderGoodsReturn> getOrderGoodsByOrdId(Integer ordId);

    /**
     * 批量修改景点集合
     * @param list
     * @return
     */
    int updateBatch(List<TicOrderGoodResponse> list);

    /**
     * 查询订单信息
     */
//    TicOrderGoods queryByColCode(String orgColCode);
    /*查询当天售票信息*/
    int queryNum(TicStaticRequest staticRequest);

    int queryNumAll(TicStaticRequest staticRequest);
}