package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TicPermission;
import org.linlinjava.litemall.db.domain.TicPermissionExample;

public interface TicPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    int countByExample(TicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    int deleteByExample(TicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    int insert(TicPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    int insertSelective(TicPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    List<TicPermission> selectByExample(TicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    TicPermission selectByPrimaryKey(Integer perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TicPermission record, @Param("example") TicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TicPermission record, @Param("example") TicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TicPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TicPermission record);
}