package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TicRefRule;
import org.linlinjava.litemall.db.domain.TicRefRuleExample;

public interface TicRefRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    int countByExample(TicRefRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    int deleteByExample(TicRefRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer refId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    int insert(TicRefRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    int insertSelective(TicRefRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    List<TicRefRule> selectByExample(TicRefRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    TicRefRule selectByPrimaryKey(Integer refId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TicRefRule record, @Param("example") TicRefRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TicRefRule record, @Param("example") TicRefRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TicRefRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TicRefRule record);
}