package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TicUser;
import org.linlinjava.litemall.db.domain.TicUserExample;

public interface TicUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    int countByExample(TicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    int deleteByExample(TicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer useId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    int insert(TicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    int insertSelective(TicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    List<TicUser> selectByExample(TicUserExample example);
    
    TicUser selectOneByExample(TicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    TicUser selectByPrimaryKey(Integer useId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TicUser record, @Param("example") TicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TicUser record, @Param("example") TicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TicUser record);
    // 逻辑删除
    int logicalDeleteByPrimaryKey(Integer id);
}