package org.linlinjava.litemall.db.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TicViewpoint;
import org.linlinjava.litemall.db.domain.TicViewpointExample;

public interface TicViewpointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int countByExample(TicViewpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int deleteByExample(TicViewpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int insert(TicViewpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int insertSelective(TicViewpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    List<TicViewpoint> selectByExampleWithBLOBs(TicViewpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    List<TicViewpoint> selectByExample(TicViewpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    TicViewpoint selectByPrimaryKey(Integer vieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TicViewpoint record, @Param("example") TicViewpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TicViewpoint record, @Param("example") TicViewpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TicViewpoint record, @Param("example") TicViewpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TicViewpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TicViewpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TicViewpoint record);

    /**
     * 条件查询 （排序）
     * @param map
     * @return
     * @author liuyu
     */
    List<TicViewpoint> selectVie(Map map);

    /**
     * 查询数量
     * @param
     * @return
     * @author liuyu
     */
    int selectVieCount();

    /**
     * 修改阅读量
     * @return
     * @author liuyu
     */
    int updateRead(Integer vieId);
}