package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TicAdCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public TicAdCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdcIdIsNull() {
            addCriterion("adc_id is null");
            return (Criteria) this;
        }

        public Criteria andAdcIdIsNotNull() {
            addCriterion("adc_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdcIdEqualTo(Integer value) {
            addCriterion("adc_id =", value, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcIdNotEqualTo(Integer value) {
            addCriterion("adc_id <>", value, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcIdGreaterThan(Integer value) {
            addCriterion("adc_id >", value, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("adc_id >=", value, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcIdLessThan(Integer value) {
            addCriterion("adc_id <", value, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcIdLessThanOrEqualTo(Integer value) {
            addCriterion("adc_id <=", value, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcIdIn(List<Integer> values) {
            addCriterion("adc_id in", values, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcIdNotIn(List<Integer> values) {
            addCriterion("adc_id not in", values, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcIdBetween(Integer value1, Integer value2) {
            addCriterion("adc_id between", value1, value2, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("adc_id not between", value1, value2, "adcId");
            return (Criteria) this;
        }

        public Criteria andAdcNameIsNull() {
            addCriterion("adc_name is null");
            return (Criteria) this;
        }

        public Criteria andAdcNameIsNotNull() {
            addCriterion("adc_name is not null");
            return (Criteria) this;
        }

        public Criteria andAdcNameEqualTo(String value) {
            addCriterion("adc_name =", value, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameNotEqualTo(String value) {
            addCriterion("adc_name <>", value, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameGreaterThan(String value) {
            addCriterion("adc_name >", value, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameGreaterThanOrEqualTo(String value) {
            addCriterion("adc_name >=", value, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameLessThan(String value) {
            addCriterion("adc_name <", value, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameLessThanOrEqualTo(String value) {
            addCriterion("adc_name <=", value, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameLike(String value) {
            addCriterion("adc_name like", value, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameNotLike(String value) {
            addCriterion("adc_name not like", value, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameIn(List<String> values) {
            addCriterion("adc_name in", values, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameNotIn(List<String> values) {
            addCriterion("adc_name not in", values, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameBetween(String value1, String value2) {
            addCriterion("adc_name between", value1, value2, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcNameNotBetween(String value1, String value2) {
            addCriterion("adc_name not between", value1, value2, "adcName");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsIsNull() {
            addCriterion("adc_keywords is null");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsIsNotNull() {
            addCriterion("adc_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsEqualTo(String value) {
            addCriterion("adc_keywords =", value, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsNotEqualTo(String value) {
            addCriterion("adc_keywords <>", value, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsGreaterThan(String value) {
            addCriterion("adc_keywords >", value, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("adc_keywords >=", value, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsLessThan(String value) {
            addCriterion("adc_keywords <", value, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsLessThanOrEqualTo(String value) {
            addCriterion("adc_keywords <=", value, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsLike(String value) {
            addCriterion("adc_keywords like", value, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsNotLike(String value) {
            addCriterion("adc_keywords not like", value, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsIn(List<String> values) {
            addCriterion("adc_keywords in", values, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsNotIn(List<String> values) {
            addCriterion("adc_keywords not in", values, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsBetween(String value1, String value2) {
            addCriterion("adc_keywords between", value1, value2, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcKeywordsNotBetween(String value1, String value2) {
            addCriterion("adc_keywords not between", value1, value2, "adcKeywords");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderIsNull() {
            addCriterion("adc_sort_order is null");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderIsNotNull() {
            addCriterion("adc_sort_order is not null");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderEqualTo(Byte value) {
            addCriterion("adc_sort_order =", value, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderNotEqualTo(Byte value) {
            addCriterion("adc_sort_order <>", value, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderGreaterThan(Byte value) {
            addCriterion("adc_sort_order >", value, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderGreaterThanOrEqualTo(Byte value) {
            addCriterion("adc_sort_order >=", value, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderLessThan(Byte value) {
            addCriterion("adc_sort_order <", value, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderLessThanOrEqualTo(Byte value) {
            addCriterion("adc_sort_order <=", value, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderIn(List<Byte> values) {
            addCriterion("adc_sort_order in", values, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderNotIn(List<Byte> values) {
            addCriterion("adc_sort_order not in", values, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderBetween(Byte value1, Byte value2) {
            addCriterion("adc_sort_order between", value1, value2, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcSortOrderNotBetween(Byte value1, Byte value2) {
            addCriterion("adc_sort_order not between", value1, value2, "adcSortOrder");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeIsNull() {
            addCriterion("adc_add_time is null");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeIsNotNull() {
            addCriterion("adc_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeEqualTo(Date value) {
            addCriterion("adc_add_time =", value, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeNotEqualTo(Date value) {
            addCriterion("adc_add_time <>", value, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeGreaterThan(Date value) {
            addCriterion("adc_add_time >", value, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("adc_add_time >=", value, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeLessThan(Date value) {
            addCriterion("adc_add_time <", value, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("adc_add_time <=", value, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeIn(List<Date> values) {
            addCriterion("adc_add_time in", values, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeNotIn(List<Date> values) {
            addCriterion("adc_add_time not in", values, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeBetween(Date value1, Date value2) {
            addCriterion("adc_add_time between", value1, value2, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("adc_add_time not between", value1, value2, "adcAddTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeIsNull() {
            addCriterion("adc_update_time is null");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeIsNotNull() {
            addCriterion("adc_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeEqualTo(Date value) {
            addCriterion("adc_update_time =", value, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeNotEqualTo(Date value) {
            addCriterion("adc_update_time <>", value, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeGreaterThan(Date value) {
            addCriterion("adc_update_time >", value, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("adc_update_time >=", value, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeLessThan(Date value) {
            addCriterion("adc_update_time <", value, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("adc_update_time <=", value, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeIn(List<Date> values) {
            addCriterion("adc_update_time in", values, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeNotIn(List<Date> values) {
            addCriterion("adc_update_time not in", values, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("adc_update_time between", value1, value2, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("adc_update_time not between", value1, value2, "adcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedIsNull() {
            addCriterion("adc_deleted is null");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedIsNotNull() {
            addCriterion("adc_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedEqualTo(Boolean value) {
            addCriterion("adc_deleted =", value, "adcDeleted");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedNotEqualTo(Boolean value) {
            addCriterion("adc_deleted <>", value, "adcDeleted");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedGreaterThan(Boolean value) {
            addCriterion("adc_deleted >", value, "adcDeleted");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("adc_deleted >=", value, "adcDeleted");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedLessThan(Boolean value) {
            addCriterion("adc_deleted <", value, "adcDeleted");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("adc_deleted <=", value, "adcDeleted");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedIn(List<Boolean> values) {
            addCriterion("adc_deleted in", values, "adcDeleted");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedNotIn(List<Boolean> values) {
            addCriterion("adc_deleted not in", values, "adcDeleted");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("adc_deleted between", value1, value2, "adcDeleted");
            return (Criteria) this;
        }

        public Criteria andAdcDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("adc_deleted not between", value1, value2, "adcDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_ad_category
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_ad_category
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}