package org.linlinjava.litemall.db.domain;

import java.util.Date;

public class TicAdCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ad_category.adc_id
     *
     * @mbggenerated
     */
    private Integer adcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ad_category.adc_name
     *
     * @mbggenerated
     */
    private String adcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ad_category.adc_keywords
     *
     * @mbggenerated
     */
    private String adcKeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ad_category.adc_sort_order
     *
     * @mbggenerated
     */
    private Byte adcSortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ad_category.adc_add_time
     *
     * @mbggenerated
     */
    private Date adcAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ad_category.adc_update_time
     *
     * @mbggenerated
     */
    private Date adcUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ad_category.adc_deleted
     *
     * @mbggenerated
     */
    private Boolean adcDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ad_category.adc_id
     *
     * @return the value of tic_ad_category.adc_id
     *
     * @mbggenerated
     */
    public Integer getAdcId() {
        return adcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ad_category.adc_id
     *
     * @param adcId the value for tic_ad_category.adc_id
     *
     * @mbggenerated
     */
    public void setAdcId(Integer adcId) {
        this.adcId = adcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ad_category.adc_name
     *
     * @return the value of tic_ad_category.adc_name
     *
     * @mbggenerated
     */
    public String getAdcName() {
        return adcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ad_category.adc_name
     *
     * @param adcName the value for tic_ad_category.adc_name
     *
     * @mbggenerated
     */
    public void setAdcName(String adcName) {
        this.adcName = adcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ad_category.adc_keywords
     *
     * @return the value of tic_ad_category.adc_keywords
     *
     * @mbggenerated
     */
    public String getAdcKeywords() {
        return adcKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ad_category.adc_keywords
     *
     * @param adcKeywords the value for tic_ad_category.adc_keywords
     *
     * @mbggenerated
     */
    public void setAdcKeywords(String adcKeywords) {
        this.adcKeywords = adcKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ad_category.adc_sort_order
     *
     * @return the value of tic_ad_category.adc_sort_order
     *
     * @mbggenerated
     */
    public Byte getAdcSortOrder() {
        return adcSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ad_category.adc_sort_order
     *
     * @param adcSortOrder the value for tic_ad_category.adc_sort_order
     *
     * @mbggenerated
     */
    public void setAdcSortOrder(Byte adcSortOrder) {
        this.adcSortOrder = adcSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ad_category.adc_add_time
     *
     * @return the value of tic_ad_category.adc_add_time
     *
     * @mbggenerated
     */
    public Date getAdcAddTime() {
        return adcAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ad_category.adc_add_time
     *
     * @param adcAddTime the value for tic_ad_category.adc_add_time
     *
     * @mbggenerated
     */
    public void setAdcAddTime(Date adcAddTime) {
        this.adcAddTime = adcAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ad_category.adc_update_time
     *
     * @return the value of tic_ad_category.adc_update_time
     *
     * @mbggenerated
     */
    public Date getAdcUpdateTime() {
        return adcUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ad_category.adc_update_time
     *
     * @param adcUpdateTime the value for tic_ad_category.adc_update_time
     *
     * @mbggenerated
     */
    public void setAdcUpdateTime(Date adcUpdateTime) {
        this.adcUpdateTime = adcUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ad_category.adc_deleted
     *
     * @return the value of tic_ad_category.adc_deleted
     *
     * @mbggenerated
     */
    public Boolean getAdcDeleted() {
        return adcDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ad_category.adc_deleted
     *
     * @param adcDeleted the value for tic_ad_category.adc_deleted
     *
     * @mbggenerated
     */
    public void setAdcDeleted(Boolean adcDeleted) {
        this.adcDeleted = adcDeleted;
    }
}