package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.linlinjava.litemall.db.domain.LitemallCommentExample.Criterion;

public class TicCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public TicCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
    	protected List<Criterion> comPicUrlsCriteria;

        protected List<Criterion> allCriteria;
        
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            comPicUrlsCriteria = new ArrayList<Criterion>();
        }
        
        public List<Criterion> getComPicUrlsCriteria() {
            return comPicUrlsCriteria;
        }
        
        protected void addComPicUrlsCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            comPicUrlsCriteria.add(new Criterion(condition, value, "org.linlinjava.litemall.db.mybatis.JsonStringArrayTypeHandler"));
            allCriteria = null;
        }

        protected void addComPicUrlsCriterion(String condition, String[] value1, String[] value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            comPicUrlsCriteria.add(new Criterion(condition, value1, value2, "org.linlinjava.litemall.db.mybatis.JsonStringArrayTypeHandler"));
            allCriteria = null;
        }
        
        public boolean isValid() {
        	return criteria.size() > 0
                    || comPicUrlsCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
        	if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(comPicUrlsCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andComIdIsNull() {
            addCriterion("com_id is null");
            return (Criteria) this;
        }

        public Criteria andComIdIsNotNull() {
            addCriterion("com_id is not null");
            return (Criteria) this;
        }

        public Criteria andComIdEqualTo(Integer value) {
            addCriterion("com_id =", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotEqualTo(Integer value) {
            addCriterion("com_id <>", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThan(Integer value) {
            addCriterion("com_id >", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("com_id >=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThan(Integer value) {
            addCriterion("com_id <", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThanOrEqualTo(Integer value) {
            addCriterion("com_id <=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdIn(List<Integer> values) {
            addCriterion("com_id in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotIn(List<Integer> values) {
            addCriterion("com_id not in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdBetween(Integer value1, Integer value2) {
            addCriterion("com_id between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotBetween(Integer value1, Integer value2) {
            addCriterion("com_id not between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdIsNull() {
            addCriterion("com_order_id is null");
            return (Criteria) this;
        }

        public Criteria andComOrderIdIsNotNull() {
            addCriterion("com_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andComOrderIdEqualTo(Integer value) {
            addCriterion("com_order_id =", value, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdNotEqualTo(Integer value) {
            addCriterion("com_order_id <>", value, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdGreaterThan(Integer value) {
            addCriterion("com_order_id >", value, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("com_order_id >=", value, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdLessThan(Integer value) {
            addCriterion("com_order_id <", value, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("com_order_id <=", value, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdIn(List<Integer> values) {
            addCriterion("com_order_id in", values, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdNotIn(List<Integer> values) {
            addCriterion("com_order_id not in", values, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("com_order_id between", value1, value2, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("com_order_id not between", value1, value2, "comOrderId");
            return (Criteria) this;
        }

        public Criteria andComContentIsNull() {
            addCriterion("com_content is null");
            return (Criteria) this;
        }

        public Criteria andComContentIsNotNull() {
            addCriterion("com_content is not null");
            return (Criteria) this;
        }

        public Criteria andComContentEqualTo(String value) {
            addCriterion("com_content =", value, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentNotEqualTo(String value) {
            addCriterion("com_content <>", value, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentGreaterThan(String value) {
            addCriterion("com_content >", value, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentGreaterThanOrEqualTo(String value) {
            addCriterion("com_content >=", value, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentLessThan(String value) {
            addCriterion("com_content <", value, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentLessThanOrEqualTo(String value) {
            addCriterion("com_content <=", value, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentLike(String value) {
            addCriterion("com_content like", value, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentNotLike(String value) {
            addCriterion("com_content not like", value, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentIn(List<String> values) {
            addCriterion("com_content in", values, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentNotIn(List<String> values) {
            addCriterion("com_content not in", values, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentBetween(String value1, String value2) {
            addCriterion("com_content between", value1, value2, "comContent");
            return (Criteria) this;
        }

        public Criteria andComContentNotBetween(String value1, String value2) {
            addCriterion("com_content not between", value1, value2, "comContent");
            return (Criteria) this;
        }

        public Criteria andComUserIdIsNull() {
            addCriterion("com_user_id is null");
            return (Criteria) this;
        }

        public Criteria andComUserIdIsNotNull() {
            addCriterion("com_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andComUserIdEqualTo(Integer value) {
            addCriterion("com_user_id =", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdNotEqualTo(Integer value) {
            addCriterion("com_user_id <>", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdGreaterThan(Integer value) {
            addCriterion("com_user_id >", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("com_user_id >=", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdLessThan(Integer value) {
            addCriterion("com_user_id <", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("com_user_id <=", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdIn(List<Integer> values) {
            addCriterion("com_user_id in", values, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdNotIn(List<Integer> values) {
            addCriterion("com_user_id not in", values, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdBetween(Integer value1, Integer value2) {
            addCriterion("com_user_id between", value1, value2, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("com_user_id not between", value1, value2, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComHasPictureIsNull() {
            addCriterion("com_has_picture is null");
            return (Criteria) this;
        }

        public Criteria andComHasPictureIsNotNull() {
            addCriterion("com_has_picture is not null");
            return (Criteria) this;
        }

        public Criteria andComHasPictureEqualTo(Boolean value) {
            addCriterion("com_has_picture =", value, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComHasPictureNotEqualTo(Boolean value) {
            addCriterion("com_has_picture <>", value, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComHasPictureGreaterThan(Boolean value) {
            addCriterion("com_has_picture >", value, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComHasPictureGreaterThanOrEqualTo(Boolean value) {
            addCriterion("com_has_picture >=", value, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComHasPictureLessThan(Boolean value) {
            addCriterion("com_has_picture <", value, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComHasPictureLessThanOrEqualTo(Boolean value) {
            addCriterion("com_has_picture <=", value, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComHasPictureIn(List<Boolean> values) {
            addCriterion("com_has_picture in", values, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComHasPictureNotIn(List<Boolean> values) {
            addCriterion("com_has_picture not in", values, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComHasPictureBetween(Boolean value1, Boolean value2) {
            addCriterion("com_has_picture between", value1, value2, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComHasPictureNotBetween(Boolean value1, Boolean value2) {
            addCriterion("com_has_picture not between", value1, value2, "comHasPicture");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsIsNull() {
            addCriterion("com_pic_urls is null");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsIsNotNull() {
            addCriterion("com_pic_urls is not null");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsEqualTo(String value) {
            addCriterion("com_pic_urls =", value, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsNotEqualTo(String value) {
            addCriterion("com_pic_urls <>", value, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsGreaterThan(String value) {
            addCriterion("com_pic_urls >", value, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsGreaterThanOrEqualTo(String value) {
            addCriterion("com_pic_urls >=", value, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsLessThan(String value) {
            addCriterion("com_pic_urls <", value, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsLessThanOrEqualTo(String value) {
            addCriterion("com_pic_urls <=", value, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsLike(String value) {
            addCriterion("com_pic_urls like", value, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsNotLike(String value) {
            addCriterion("com_pic_urls not like", value, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsIn(List<String> values) {
            addCriterion("com_pic_urls in", values, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsNotIn(List<String> values) {
            addCriterion("com_pic_urls not in", values, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsBetween(String value1, String value2) {
            addCriterion("com_pic_urls between", value1, value2, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComPicUrlsNotBetween(String value1, String value2) {
            addCriterion("com_pic_urls not between", value1, value2, "comPicUrls");
            return (Criteria) this;
        }

        public Criteria andComLikeIsNull() {
            addCriterion("com_like is null");
            return (Criteria) this;
        }

        public Criteria andComLikeIsNotNull() {
            addCriterion("com_like is not null");
            return (Criteria) this;
        }

        public Criteria andComLikeEqualTo(Integer value) {
            addCriterion("com_like =", value, "comLike");
            return (Criteria) this;
        }

        public Criteria andComLikeNotEqualTo(Integer value) {
            addCriterion("com_like <>", value, "comLike");
            return (Criteria) this;
        }

        public Criteria andComLikeGreaterThan(Integer value) {
            addCriterion("com_like >", value, "comLike");
            return (Criteria) this;
        }

        public Criteria andComLikeGreaterThanOrEqualTo(Integer value) {
            addCriterion("com_like >=", value, "comLike");
            return (Criteria) this;
        }

        public Criteria andComLikeLessThan(Integer value) {
            addCriterion("com_like <", value, "comLike");
            return (Criteria) this;
        }

        public Criteria andComLikeLessThanOrEqualTo(Integer value) {
            addCriterion("com_like <=", value, "comLike");
            return (Criteria) this;
        }

        public Criteria andComLikeIn(List<Integer> values) {
            addCriterion("com_like in", values, "comLike");
            return (Criteria) this;
        }

        public Criteria andComLikeNotIn(List<Integer> values) {
            addCriterion("com_like not in", values, "comLike");
            return (Criteria) this;
        }

        public Criteria andComLikeBetween(Integer value1, Integer value2) {
            addCriterion("com_like between", value1, value2, "comLike");
            return (Criteria) this;
        }

        public Criteria andComLikeNotBetween(Integer value1, Integer value2) {
            addCriterion("com_like not between", value1, value2, "comLike");
            return (Criteria) this;
        }

        public Criteria andComStarIsNull() {
            addCriterion("com_star is null");
            return (Criteria) this;
        }

        public Criteria andComStarIsNotNull() {
            addCriterion("com_star is not null");
            return (Criteria) this;
        }

        public Criteria andComStarEqualTo(String value) {
            addCriterion("com_star =", value, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarNotEqualTo(String value) {
            addCriterion("com_star <>", value, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarGreaterThan(String value) {
            addCriterion("com_star >", value, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarGreaterThanOrEqualTo(String value) {
            addCriterion("com_star >=", value, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarLessThan(String value) {
            addCriterion("com_star <", value, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarLessThanOrEqualTo(String value) {
            addCriterion("com_star <=", value, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarLike(String value) {
            addCriterion("com_star like", value, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarNotLike(String value) {
            addCriterion("com_star not like", value, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarIn(List<String> values) {
            addCriterion("com_star in", values, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarNotIn(List<String> values) {
            addCriterion("com_star not in", values, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarBetween(String value1, String value2) {
            addCriterion("com_star between", value1, value2, "comStar");
            return (Criteria) this;
        }

        public Criteria andComStarNotBetween(String value1, String value2) {
            addCriterion("com_star not between", value1, value2, "comStar");
            return (Criteria) this;
        }

        public Criteria andComViewpointIsNull() {
            addCriterion("com_viewpoint is null");
            return (Criteria) this;
        }

        public Criteria andComViewpointIsNotNull() {
            addCriterion("com_viewpoint is not null");
            return (Criteria) this;
        }

        public Criteria andComViewpointEqualTo(String value) {
            addCriterion("com_viewpoint =", value, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointNotEqualTo(String value) {
            addCriterion("com_viewpoint <>", value, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointGreaterThan(String value) {
            addCriterion("com_viewpoint >", value, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointGreaterThanOrEqualTo(String value) {
            addCriterion("com_viewpoint >=", value, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointLessThan(String value) {
            addCriterion("com_viewpoint <", value, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointLessThanOrEqualTo(String value) {
            addCriterion("com_viewpoint <=", value, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointLike(String value) {
            addCriterion("com_viewpoint like", value, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointNotLike(String value) {
            addCriterion("com_viewpoint not like", value, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointIn(List<String> values) {
            addCriterion("com_viewpoint in", values, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointNotIn(List<String> values) {
            addCriterion("com_viewpoint not in", values, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointBetween(String value1, String value2) {
            addCriterion("com_viewpoint between", value1, value2, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComViewpointNotBetween(String value1, String value2) {
            addCriterion("com_viewpoint not between", value1, value2, "comViewpoint");
            return (Criteria) this;
        }

        public Criteria andComIsgoodIsNull() {
            addCriterion("com_isgood is null");
            return (Criteria) this;
        }

        public Criteria andComIsgoodIsNotNull() {
            addCriterion("com_isgood is not null");
            return (Criteria) this;
        }

        public Criteria andComIsgoodEqualTo(Boolean value) {
            addCriterion("com_isgood =", value, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComIsgoodNotEqualTo(Boolean value) {
            addCriterion("com_isgood <>", value, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComIsgoodGreaterThan(Boolean value) {
            addCriterion("com_isgood >", value, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComIsgoodGreaterThanOrEqualTo(Boolean value) {
            addCriterion("com_isgood >=", value, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComIsgoodLessThan(Boolean value) {
            addCriterion("com_isgood <", value, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComIsgoodLessThanOrEqualTo(Boolean value) {
            addCriterion("com_isgood <=", value, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComIsgoodIn(List<Boolean> values) {
            addCriterion("com_isgood in", values, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComIsgoodNotIn(List<Boolean> values) {
            addCriterion("com_isgood not in", values, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComIsgoodBetween(Boolean value1, Boolean value2) {
            addCriterion("com_isgood between", value1, value2, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComIsgoodNotBetween(Boolean value1, Boolean value2) {
            addCriterion("com_isgood not between", value1, value2, "comIsgood");
            return (Criteria) this;
        }

        public Criteria andComAddTimeIsNull() {
            addCriterion("com_add_time is null");
            return (Criteria) this;
        }

        public Criteria andComAddTimeIsNotNull() {
            addCriterion("com_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andComAddTimeEqualTo(Date value) {
            addCriterion("com_add_time =", value, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComAddTimeNotEqualTo(Date value) {
            addCriterion("com_add_time <>", value, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComAddTimeGreaterThan(Date value) {
            addCriterion("com_add_time >", value, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("com_add_time >=", value, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComAddTimeLessThan(Date value) {
            addCriterion("com_add_time <", value, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("com_add_time <=", value, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComAddTimeIn(List<Date> values) {
            addCriterion("com_add_time in", values, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComAddTimeNotIn(List<Date> values) {
            addCriterion("com_add_time not in", values, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComAddTimeBetween(Date value1, Date value2) {
            addCriterion("com_add_time between", value1, value2, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("com_add_time not between", value1, value2, "comAddTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeIsNull() {
            addCriterion("com_update_time is null");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeIsNotNull() {
            addCriterion("com_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeEqualTo(Date value) {
            addCriterion("com_update_time =", value, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeNotEqualTo(Date value) {
            addCriterion("com_update_time <>", value, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeGreaterThan(Date value) {
            addCriterion("com_update_time >", value, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("com_update_time >=", value, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeLessThan(Date value) {
            addCriterion("com_update_time <", value, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("com_update_time <=", value, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeIn(List<Date> values) {
            addCriterion("com_update_time in", values, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeNotIn(List<Date> values) {
            addCriterion("com_update_time not in", values, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("com_update_time between", value1, value2, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("com_update_time not between", value1, value2, "comUpdateTime");
            return (Criteria) this;
        }

        public Criteria andComDeletedIsNull() {
            addCriterion("com_deleted is null");
            return (Criteria) this;
        }

        public Criteria andComDeletedIsNotNull() {
            addCriterion("com_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andComDeletedEqualTo(Boolean value) {
            addCriterion("com_deleted =", value, "comDeleted");
            return (Criteria) this;
        }

        public Criteria andComDeletedNotEqualTo(Boolean value) {
            addCriterion("com_deleted <>", value, "comDeleted");
            return (Criteria) this;
        }

        public Criteria andComDeletedGreaterThan(Boolean value) {
            addCriterion("com_deleted >", value, "comDeleted");
            return (Criteria) this;
        }

        public Criteria andComDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("com_deleted >=", value, "comDeleted");
            return (Criteria) this;
        }

        public Criteria andComDeletedLessThan(Boolean value) {
            addCriterion("com_deleted <", value, "comDeleted");
            return (Criteria) this;
        }

        public Criteria andComDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("com_deleted <=", value, "comDeleted");
            return (Criteria) this;
        }

        public Criteria andComDeletedIn(List<Boolean> values) {
            addCriterion("com_deleted in", values, "comDeleted");
            return (Criteria) this;
        }

        public Criteria andComDeletedNotIn(List<Boolean> values) {
            addCriterion("com_deleted not in", values, "comDeleted");
            return (Criteria) this;
        }

        public Criteria andComDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("com_deleted between", value1, value2, "comDeleted");
            return (Criteria) this;
        }

        public Criteria andComDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("com_deleted not between", value1, value2, "comDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_comment
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_comment
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}