package org.linlinjava.litemall.db.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.time.LocalDateTime;

public class TicCouponUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_id
     *
     * @mbggenerated
     */
    private Integer cosId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_user_id
     *
     * @mbggenerated
     */
    private Integer cosUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_coupon_id
     *
     * @mbggenerated
     */
    private Integer cosCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_status
     *
     * @mbggenerated
     */
    private Short cosStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_used_time
     *
     * @mbggenerated
     */
    private LocalDateTime cosUsedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_start_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    private LocalDateTime cosStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_end_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    private LocalDateTime cosEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_order_id
     *
     * @mbggenerated
     */
    private Integer cosOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_add_time
     *
     * @mbggenerated
     */
    private LocalDateTime cosAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_update_time
     *
     * @mbggenerated
     */
    private LocalDateTime cosUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon_user.cos_deleted
     *
     * @mbggenerated
     */
    private Boolean cosDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_id
     *
     * @return the value of tic_coupon_user.cos_id
     *
     * @mbggenerated
     */
    public Integer getCosId() {
        return cosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_id
     *
     * @param cosId the value for tic_coupon_user.cos_id
     *
     * @mbggenerated
     */
    public void setCosId(Integer cosId) {
        this.cosId = cosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_user_id
     *
     * @return the value of tic_coupon_user.cos_user_id
     *
     * @mbggenerated
     */
    public Integer getCosUserId() {
        return cosUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_user_id
     *
     * @param cosUserId the value for tic_coupon_user.cos_user_id
     *
     * @mbggenerated
     */
    public void setCosUserId(Integer cosUserId) {
        this.cosUserId = cosUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_coupon_id
     *
     * @return the value of tic_coupon_user.cos_coupon_id
     *
     * @mbggenerated
     */
    public Integer getCosCouponId() {
        return cosCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_coupon_id
     *
     * @param cosCouponId the value for tic_coupon_user.cos_coupon_id
     *
     * @mbggenerated
     */
    public void setCosCouponId(Integer cosCouponId) {
        this.cosCouponId = cosCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_status
     *
     * @return the value of tic_coupon_user.cos_status
     *
     * @mbggenerated
     */
    public Short getCosStatus() {
        return cosStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_status
     *
     * @param cosStatus the value for tic_coupon_user.cos_status
     *
     * @mbggenerated
     */
    public void setCosStatus(Short cosStatus) {
        this.cosStatus = cosStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_used_time
     *
     * @return the value of tic_coupon_user.cos_used_time
     *
     * @mbggenerated
     */
    public LocalDateTime getCosUsedTime() {
        return cosUsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_used_time
     *
     * @param cosUsedTime the value for tic_coupon_user.cos_used_time
     *
     * @mbggenerated
     */
    public void setCosUsedTime(LocalDateTime cosUsedTime) {
        this.cosUsedTime = cosUsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_start_time
     *
     * @return the value of tic_coupon_user.cos_start_time
     *
     * @mbggenerated
     */
    public LocalDateTime getCosStartTime() {
        return cosStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_start_time
     *
     * @param cosStartTime the value for tic_coupon_user.cos_start_time
     *
     * @mbggenerated
     */
    public void setCosStartTime(LocalDateTime cosStartTime) {
        this.cosStartTime = cosStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_end_time
     *
     * @return the value of tic_coupon_user.cos_end_time
     *
     * @mbggenerated
     */
    public LocalDateTime getCosEndTime() {
        return cosEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_end_time
     *
     * @param cosEndTime the value for tic_coupon_user.cos_end_time
     *
     * @mbggenerated
     */
    public void setCosEndTime(LocalDateTime cosEndTime) {
        this.cosEndTime = cosEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_order_id
     *
     * @return the value of tic_coupon_user.cos_order_id
     *
     * @mbggenerated
     */
    public Integer getCosOrderId() {
        return cosOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_order_id
     *
     * @param cosOrderId the value for tic_coupon_user.cos_order_id
     *
     * @mbggenerated
     */
    public void setCosOrderId(Integer cosOrderId) {
        this.cosOrderId = cosOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_add_time
     *
     * @return the value of tic_coupon_user.cos_add_time
     *
     * @mbggenerated
     */
    public LocalDateTime getCosAddTime() {
        return cosAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_add_time
     *
     * @param cosAddTime the value for tic_coupon_user.cos_add_time
     *
     * @mbggenerated
     */
    public void setCosAddTime(LocalDateTime cosAddTime) {
        this.cosAddTime = cosAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_update_time
     *
     * @return the value of tic_coupon_user.cos_update_time
     *
     * @mbggenerated
     */
    public LocalDateTime getCosUpdateTime() {
        return cosUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_update_time
     *
     * @param cosUpdateTime the value for tic_coupon_user.cos_update_time
     *
     * @mbggenerated
     */
    public void setCosUpdateTime(LocalDateTime cosUpdateTime) {
        this.cosUpdateTime = cosUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon_user.cos_deleted
     *
     * @return the value of tic_coupon_user.cos_deleted
     *
     * @mbggenerated
     */
    public Boolean getCosDeleted() {
        return cosDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon_user.cos_deleted
     *
     * @param cosDeleted the value for tic_coupon_user.cos_deleted
     *
     * @mbggenerated
     */
    public void setCosDeleted(Boolean cosDeleted) {
        this.cosDeleted = cosDeleted;
    }
}