package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.linlinjava.litemall.db.domain.LitemallCouponExample.Criteria;
import org.linlinjava.litemall.db.domain.LitemallCouponExample.GeneratedCriteria;
import org.linlinjava.litemall.db.domain.LitemallCouponExample.Criteria.ICriteriaAdd;

public class TicCouponExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public TicCouponExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        TicCouponExample example = new TicCouponExample();
        return example.createCriteria();
    }
    
    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> couGoodsValueCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            couGoodsValueCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getCouGoodsValueCriteria() {
            return couGoodsValueCriteria;
        }

        protected void addCouGoodsValueCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            couGoodsValueCriteria.add(new Criterion(condition, value, "org.linlinjava.litemall.db.mybatis.JsonIntegerArrayTypeHandler"));
            allCriteria = null;
        }

        protected void addCouGoodsValueCriterion(String condition, Integer[] value1, Integer[] value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            couGoodsValueCriteria.add(new Criterion(condition, value1, value2, "org.linlinjava.litemall.db.mybatis.JsonIntegerArrayTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || couGoodsValueCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(couGoodsValueCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andCouIdIsNull() {
            addCriterion("cou_id is null");
            return (Criteria) this;
        }

        public Criteria andCouIdIsNotNull() {
            addCriterion("cou_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouIdEqualTo(Integer value) {
            addCriterion("cou_id =", value, "couId");
            return (Criteria) this;
        }

        public Criteria andCouIdNotEqualTo(Integer value) {
            addCriterion("cou_id <>", value, "couId");
            return (Criteria) this;
        }

        public Criteria andCouIdGreaterThan(Integer value) {
            addCriterion("cou_id >", value, "couId");
            return (Criteria) this;
        }

        public Criteria andCouIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cou_id >=", value, "couId");
            return (Criteria) this;
        }

        public Criteria andCouIdLessThan(Integer value) {
            addCriterion("cou_id <", value, "couId");
            return (Criteria) this;
        }

        public Criteria andCouIdLessThanOrEqualTo(Integer value) {
            addCriterion("cou_id <=", value, "couId");
            return (Criteria) this;
        }

        public Criteria andCouIdIn(List<Integer> values) {
            addCriterion("cou_id in", values, "couId");
            return (Criteria) this;
        }

        public Criteria andCouIdNotIn(List<Integer> values) {
            addCriterion("cou_id not in", values, "couId");
            return (Criteria) this;
        }

        public Criteria andCouIdBetween(Integer value1, Integer value2) {
            addCriterion("cou_id between", value1, value2, "couId");
            return (Criteria) this;
        }

        public Criteria andCouIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cou_id not between", value1, value2, "couId");
            return (Criteria) this;
        }

        public Criteria andCouNameIsNull() {
            addCriterion("cou_name is null");
            return (Criteria) this;
        }

        public Criteria andCouNameIsNotNull() {
            addCriterion("cou_name is not null");
            return (Criteria) this;
        }

        public Criteria andCouNameEqualTo(String value) {
            addCriterion("cou_name =", value, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameNotEqualTo(String value) {
            addCriterion("cou_name <>", value, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameGreaterThan(String value) {
            addCriterion("cou_name >", value, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameGreaterThanOrEqualTo(String value) {
            addCriterion("cou_name >=", value, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameLessThan(String value) {
            addCriterion("cou_name <", value, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameLessThanOrEqualTo(String value) {
            addCriterion("cou_name <=", value, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameLike(String value) {
            addCriterion("cou_name like", value, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameNotLike(String value) {
            addCriterion("cou_name not like", value, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameIn(List<String> values) {
            addCriterion("cou_name in", values, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameNotIn(List<String> values) {
            addCriterion("cou_name not in", values, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameBetween(String value1, String value2) {
            addCriterion("cou_name between", value1, value2, "couName");
            return (Criteria) this;
        }

        public Criteria andCouNameNotBetween(String value1, String value2) {
            addCriterion("cou_name not between", value1, value2, "couName");
            return (Criteria) this;
        }

        public Criteria andCouDescIsNull() {
            addCriterion("cou_desc is null");
            return (Criteria) this;
        }

        public Criteria andCouDescIsNotNull() {
            addCriterion("cou_desc is not null");
            return (Criteria) this;
        }

        public Criteria andCouDescEqualTo(String value) {
            addCriterion("cou_desc =", value, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescNotEqualTo(String value) {
            addCriterion("cou_desc <>", value, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescGreaterThan(String value) {
            addCriterion("cou_desc >", value, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescGreaterThanOrEqualTo(String value) {
            addCriterion("cou_desc >=", value, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescLessThan(String value) {
            addCriterion("cou_desc <", value, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescLessThanOrEqualTo(String value) {
            addCriterion("cou_desc <=", value, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescLike(String value) {
            addCriterion("cou_desc like", value, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescNotLike(String value) {
            addCriterion("cou_desc not like", value, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescIn(List<String> values) {
            addCriterion("cou_desc in", values, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescNotIn(List<String> values) {
            addCriterion("cou_desc not in", values, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescBetween(String value1, String value2) {
            addCriterion("cou_desc between", value1, value2, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouDescNotBetween(String value1, String value2) {
            addCriterion("cou_desc not between", value1, value2, "couDesc");
            return (Criteria) this;
        }

        public Criteria andCouTagIsNull() {
            addCriterion("cou_tag is null");
            return (Criteria) this;
        }

        public Criteria andCouTagIsNotNull() {
            addCriterion("cou_tag is not null");
            return (Criteria) this;
        }

        public Criteria andCouTagEqualTo(String value) {
            addCriterion("cou_tag =", value, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagNotEqualTo(String value) {
            addCriterion("cou_tag <>", value, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagGreaterThan(String value) {
            addCriterion("cou_tag >", value, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagGreaterThanOrEqualTo(String value) {
            addCriterion("cou_tag >=", value, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagLessThan(String value) {
            addCriterion("cou_tag <", value, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagLessThanOrEqualTo(String value) {
            addCriterion("cou_tag <=", value, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagLike(String value) {
            addCriterion("cou_tag like", value, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagNotLike(String value) {
            addCriterion("cou_tag not like", value, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagIn(List<String> values) {
            addCriterion("cou_tag in", values, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagNotIn(List<String> values) {
            addCriterion("cou_tag not in", values, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagBetween(String value1, String value2) {
            addCriterion("cou_tag between", value1, value2, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTagNotBetween(String value1, String value2) {
            addCriterion("cou_tag not between", value1, value2, "couTag");
            return (Criteria) this;
        }

        public Criteria andCouTotalIsNull() {
            addCriterion("cou_total is null");
            return (Criteria) this;
        }

        public Criteria andCouTotalIsNotNull() {
            addCriterion("cou_total is not null");
            return (Criteria) this;
        }

        public Criteria andCouTotalEqualTo(Integer value) {
            addCriterion("cou_total =", value, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouTotalNotEqualTo(Integer value) {
            addCriterion("cou_total <>", value, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouTotalGreaterThan(Integer value) {
            addCriterion("cou_total >", value, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("cou_total >=", value, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouTotalLessThan(Integer value) {
            addCriterion("cou_total <", value, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouTotalLessThanOrEqualTo(Integer value) {
            addCriterion("cou_total <=", value, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouTotalIn(List<Integer> values) {
            addCriterion("cou_total in", values, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouTotalNotIn(List<Integer> values) {
            addCriterion("cou_total not in", values, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouTotalBetween(Integer value1, Integer value2) {
            addCriterion("cou_total between", value1, value2, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("cou_total not between", value1, value2, "couTotal");
            return (Criteria) this;
        }

        public Criteria andCouGetCountIsNull() {
            addCriterion("cou_get_count is null");
            return (Criteria) this;
        }

        public Criteria andCouGetCountIsNotNull() {
            addCriterion("cou_get_count is not null");
            return (Criteria) this;
        }

        public Criteria andCouGetCountEqualTo(Integer value) {
            addCriterion("cou_get_count =", value, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouGetCountNotEqualTo(Integer value) {
            addCriterion("cou_get_count <>", value, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouGetCountGreaterThan(Integer value) {
            addCriterion("cou_get_count >", value, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouGetCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("cou_get_count >=", value, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouGetCountLessThan(Integer value) {
            addCriterion("cou_get_count <", value, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouGetCountLessThanOrEqualTo(Integer value) {
            addCriterion("cou_get_count <=", value, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouGetCountIn(List<Integer> values) {
            addCriterion("cou_get_count in", values, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouGetCountNotIn(List<Integer> values) {
            addCriterion("cou_get_count not in", values, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouGetCountBetween(Integer value1, Integer value2) {
            addCriterion("cou_get_count between", value1, value2, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouGetCountNotBetween(Integer value1, Integer value2) {
            addCriterion("cou_get_count not between", value1, value2, "couGetCount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountIsNull() {
            addCriterion("cou_discount is null");
            return (Criteria) this;
        }

        public Criteria andCouDiscountIsNotNull() {
            addCriterion("cou_discount is not null");
            return (Criteria) this;
        }

        public Criteria andCouDiscountEqualTo(BigDecimal value) {
            addCriterion("cou_discount =", value, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountNotEqualTo(BigDecimal value) {
            addCriterion("cou_discount <>", value, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountGreaterThan(BigDecimal value) {
            addCriterion("cou_discount >", value, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cou_discount >=", value, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountLessThan(BigDecimal value) {
            addCriterion("cou_discount <", value, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cou_discount <=", value, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountIn(List<BigDecimal> values) {
            addCriterion("cou_discount in", values, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountNotIn(List<BigDecimal> values) {
            addCriterion("cou_discount not in", values, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cou_discount between", value1, value2, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouDiscountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cou_discount not between", value1, value2, "couDiscount");
            return (Criteria) this;
        }

        public Criteria andCouMinIsNull() {
            addCriterion("cou_min is null");
            return (Criteria) this;
        }

        public Criteria andCouMinIsNotNull() {
            addCriterion("cou_min is not null");
            return (Criteria) this;
        }

        public Criteria andCouMinEqualTo(BigDecimal value) {
            addCriterion("cou_min =", value, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouMinNotEqualTo(BigDecimal value) {
            addCriterion("cou_min <>", value, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouMinGreaterThan(BigDecimal value) {
            addCriterion("cou_min >", value, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouMinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cou_min >=", value, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouMinLessThan(BigDecimal value) {
            addCriterion("cou_min <", value, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouMinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cou_min <=", value, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouMinIn(List<BigDecimal> values) {
            addCriterion("cou_min in", values, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouMinNotIn(List<BigDecimal> values) {
            addCriterion("cou_min not in", values, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouMinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cou_min between", value1, value2, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouMinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cou_min not between", value1, value2, "couMin");
            return (Criteria) this;
        }

        public Criteria andCouLimitIsNull() {
            addCriterion("cou_limit is null");
            return (Criteria) this;
        }

        public Criteria andCouLimitIsNotNull() {
            addCriterion("cou_limit is not null");
            return (Criteria) this;
        }

        public Criteria andCouLimitEqualTo(Short value) {
            addCriterion("cou_limit =", value, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouLimitNotEqualTo(Short value) {
            addCriterion("cou_limit <>", value, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouLimitGreaterThan(Short value) {
            addCriterion("cou_limit >", value, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouLimitGreaterThanOrEqualTo(Short value) {
            addCriterion("cou_limit >=", value, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouLimitLessThan(Short value) {
            addCriterion("cou_limit <", value, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouLimitLessThanOrEqualTo(Short value) {
            addCriterion("cou_limit <=", value, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouLimitIn(List<Short> values) {
            addCriterion("cou_limit in", values, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouLimitNotIn(List<Short> values) {
            addCriterion("cou_limit not in", values, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouLimitBetween(Short value1, Short value2) {
            addCriterion("cou_limit between", value1, value2, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouLimitNotBetween(Short value1, Short value2) {
            addCriterion("cou_limit not between", value1, value2, "couLimit");
            return (Criteria) this;
        }

        public Criteria andCouTypeIsNull() {
            addCriterion("cou_type is null");
            return (Criteria) this;
        }

        public Criteria andCouTypeIsNotNull() {
            addCriterion("cou_type is not null");
            return (Criteria) this;
        }

        public Criteria andCouTypeEqualTo(Short value) {
            addCriterion("cou_type =", value, "couType");
            return (Criteria) this;
        }

        public Criteria andCouTypeNotEqualTo(Short value) {
            addCriterion("cou_type <>", value, "couType");
            return (Criteria) this;
        }

        public Criteria andCouTypeGreaterThan(Short value) {
            addCriterion("cou_type >", value, "couType");
            return (Criteria) this;
        }

        public Criteria andCouTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("cou_type >=", value, "couType");
            return (Criteria) this;
        }

        public Criteria andCouTypeLessThan(Short value) {
            addCriterion("cou_type <", value, "couType");
            return (Criteria) this;
        }

        public Criteria andCouTypeLessThanOrEqualTo(Short value) {
            addCriterion("cou_type <=", value, "couType");
            return (Criteria) this;
        }

        public Criteria andCouTypeIn(List<Short> values) {
            addCriterion("cou_type in", values, "couType");
            return (Criteria) this;
        }

        public Criteria andCouTypeNotIn(List<Short> values) {
            addCriterion("cou_type not in", values, "couType");
            return (Criteria) this;
        }

        public Criteria andCouTypeBetween(Short value1, Short value2) {
            addCriterion("cou_type between", value1, value2, "couType");
            return (Criteria) this;
        }

        public Criteria andCouTypeNotBetween(Short value1, Short value2) {
            addCriterion("cou_type not between", value1, value2, "couType");
            return (Criteria) this;
        }

        public Criteria andCouStatusIsNull() {
            addCriterion("cou_status is null");
            return (Criteria) this;
        }

        public Criteria andCouStatusIsNotNull() {
            addCriterion("cou_status is not null");
            return (Criteria) this;
        }

        public Criteria andCouStatusEqualTo(Short value) {
            addCriterion("cou_status =", value, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouStatusNotEqualTo(Short value) {
            addCriterion("cou_status <>", value, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouStatusGreaterThan(Short value) {
            addCriterion("cou_status >", value, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("cou_status >=", value, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouStatusLessThan(Short value) {
            addCriterion("cou_status <", value, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouStatusLessThanOrEqualTo(Short value) {
            addCriterion("cou_status <=", value, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouStatusIn(List<Short> values) {
            addCriterion("cou_status in", values, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouStatusNotIn(List<Short> values) {
            addCriterion("cou_status not in", values, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouStatusBetween(Short value1, Short value2) {
            addCriterion("cou_status between", value1, value2, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouStatusNotBetween(Short value1, Short value2) {
            addCriterion("cou_status not between", value1, value2, "couStatus");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeIsNull() {
            addCriterion("cou_goods_type is null");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeIsNotNull() {
            addCriterion("cou_goods_type is not null");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeEqualTo(Short value) {
            addCriterion("cou_goods_type =", value, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeNotEqualTo(Short value) {
            addCriterion("cou_goods_type <>", value, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeGreaterThan(Short value) {
            addCriterion("cou_goods_type >", value, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("cou_goods_type >=", value, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeLessThan(Short value) {
            addCriterion("cou_goods_type <", value, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeLessThanOrEqualTo(Short value) {
            addCriterion("cou_goods_type <=", value, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeIn(List<Short> values) {
            addCriterion("cou_goods_type in", values, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeNotIn(List<Short> values) {
            addCriterion("cou_goods_type not in", values, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeBetween(Short value1, Short value2) {
            addCriterion("cou_goods_type between", value1, value2, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsTypeNotBetween(Short value1, Short value2) {
            addCriterion("cou_goods_type not between", value1, value2, "couGoodsType");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueIsNull() {
            addCriterion("cou_goods_value is null");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueIsNotNull() {
            addCriterion("cou_goods_value is not null");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueEqualTo(Integer[] value) {
            addCouGoodsValueCriterion("cou_goods_value =", value, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueNotEqualTo(Integer[] value) {
            addCouGoodsValueCriterion("cou_goods_value <>", value, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueGreaterThan(Integer[] value) {
            addCouGoodsValueCriterion("cou_goods_value >", value, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueGreaterThanOrEqualTo(Integer[] value) {
            addCouGoodsValueCriterion("cou_goods_value >=", value, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueLessThan(Integer[] value) {
            addCouGoodsValueCriterion("cou_goods_value <", value, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueLessThanOrEqualTo(Integer[] value) {
            addCouGoodsValueCriterion("cou_goods_value <=", value, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueLike(Integer[] value) {
            addCouGoodsValueCriterion("cou_goods_value like", value, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueNotLike(Integer[] value) {
            addCouGoodsValueCriterion("cou_goods_value not like", value, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueIn(List<Integer[]> values) {
            addCouGoodsValueCriterion("cou_goods_value in", values, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueNotIn(List<Integer[]> values) {
            addCouGoodsValueCriterion("cou_goods_value not in", values, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueBetween(Integer[] value1, Integer[] value2) {
            addCouGoodsValueCriterion("cou_goods_value between", value1, value2, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouGoodsValueNotBetween(Integer[] value1, Integer[] value2) {
            addCouGoodsValueCriterion("cou_goods_value not between", value1, value2, "couGoodsValue");
            return (Criteria) this;
        }

        public Criteria andCouCodeIsNull() {
            addCriterion("cou_code is null");
            return (Criteria) this;
        }

        public Criteria andCouCodeIsNotNull() {
            addCriterion("cou_code is not null");
            return (Criteria) this;
        }

        public Criteria andCouCodeEqualTo(String value) {
            addCriterion("cou_code =", value, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeNotEqualTo(String value) {
            addCriterion("cou_code <>", value, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeGreaterThan(String value) {
            addCriterion("cou_code >", value, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeGreaterThanOrEqualTo(String value) {
            addCriterion("cou_code >=", value, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeLessThan(String value) {
            addCriterion("cou_code <", value, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeLessThanOrEqualTo(String value) {
            addCriterion("cou_code <=", value, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeLike(String value) {
            addCriterion("cou_code like", value, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeNotLike(String value) {
            addCriterion("cou_code not like", value, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeIn(List<String> values) {
            addCriterion("cou_code in", values, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeNotIn(List<String> values) {
            addCriterion("cou_code not in", values, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeBetween(String value1, String value2) {
            addCriterion("cou_code between", value1, value2, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouCodeNotBetween(String value1, String value2) {
            addCriterion("cou_code not between", value1, value2, "couCode");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeIsNull() {
            addCriterion("cou_time_type is null");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeIsNotNull() {
            addCriterion("cou_time_type is not null");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeEqualTo(Short value) {
            addCriterion("cou_time_type =", value, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeNotEqualTo(Short value) {
            addCriterion("cou_time_type <>", value, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeGreaterThan(Short value) {
            addCriterion("cou_time_type >", value, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("cou_time_type >=", value, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeLessThan(Short value) {
            addCriterion("cou_time_type <", value, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeLessThanOrEqualTo(Short value) {
            addCriterion("cou_time_type <=", value, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeIn(List<Short> values) {
            addCriterion("cou_time_type in", values, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeNotIn(List<Short> values) {
            addCriterion("cou_time_type not in", values, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeBetween(Short value1, Short value2) {
            addCriterion("cou_time_type between", value1, value2, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouTimeTypeNotBetween(Short value1, Short value2) {
            addCriterion("cou_time_type not between", value1, value2, "couTimeType");
            return (Criteria) this;
        }

        public Criteria andCouDaysIsNull() {
            addCriterion("cou_days is null");
            return (Criteria) this;
        }

        public Criteria andCouDaysIsNotNull() {
            addCriterion("cou_days is not null");
            return (Criteria) this;
        }

        public Criteria andCouDaysEqualTo(Short value) {
            addCriterion("cou_days =", value, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouDaysNotEqualTo(Short value) {
            addCriterion("cou_days <>", value, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouDaysGreaterThan(Short value) {
            addCriterion("cou_days >", value, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouDaysGreaterThanOrEqualTo(Short value) {
            addCriterion("cou_days >=", value, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouDaysLessThan(Short value) {
            addCriterion("cou_days <", value, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouDaysLessThanOrEqualTo(Short value) {
            addCriterion("cou_days <=", value, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouDaysIn(List<Short> values) {
            addCriterion("cou_days in", values, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouDaysNotIn(List<Short> values) {
            addCriterion("cou_days not in", values, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouDaysBetween(Short value1, Short value2) {
            addCriterion("cou_days between", value1, value2, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouDaysNotBetween(Short value1, Short value2) {
            addCriterion("cou_days not between", value1, value2, "couDays");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeIsNull() {
            addCriterion("cou_start_time is null");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeIsNotNull() {
            addCriterion("cou_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeEqualTo(Date value) {
            addCriterion("cou_start_time =", value, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeNotEqualTo(Date value) {
            addCriterion("cou_start_time <>", value, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeGreaterThan(Date value) {
            addCriterion("cou_start_time >", value, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cou_start_time >=", value, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeLessThan(Date value) {
            addCriterion("cou_start_time <", value, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("cou_start_time <=", value, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeIn(List<Date> values) {
            addCriterion("cou_start_time in", values, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeNotIn(List<Date> values) {
            addCriterion("cou_start_time not in", values, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeBetween(Date value1, Date value2) {
            addCriterion("cou_start_time between", value1, value2, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("cou_start_time not between", value1, value2, "couStartTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeIsNull() {
            addCriterion("cou_end_time is null");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeIsNotNull() {
            addCriterion("cou_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeEqualTo(Date value) {
            addCriterion("cou_end_time =", value, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeNotEqualTo(Date value) {
            addCriterion("cou_end_time <>", value, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeGreaterThan(Date value) {
            addCriterion("cou_end_time >", value, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cou_end_time >=", value, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeLessThan(Date value) {
            addCriterion("cou_end_time <", value, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("cou_end_time <=", value, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeIn(List<Date> values) {
            addCriterion("cou_end_time in", values, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeNotIn(List<Date> values) {
            addCriterion("cou_end_time not in", values, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeBetween(Date value1, Date value2) {
            addCriterion("cou_end_time between", value1, value2, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("cou_end_time not between", value1, value2, "couEndTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeIsNull() {
            addCriterion("cou_add_time is null");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeIsNotNull() {
            addCriterion("cou_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeEqualTo(Date value) {
            addCriterion("cou_add_time =", value, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeNotEqualTo(Date value) {
            addCriterion("cou_add_time <>", value, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeGreaterThan(Date value) {
            addCriterion("cou_add_time >", value, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cou_add_time >=", value, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeLessThan(Date value) {
            addCriterion("cou_add_time <", value, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("cou_add_time <=", value, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeIn(List<Date> values) {
            addCriterion("cou_add_time in", values, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeNotIn(List<Date> values) {
            addCriterion("cou_add_time not in", values, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeBetween(Date value1, Date value2) {
            addCriterion("cou_add_time between", value1, value2, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("cou_add_time not between", value1, value2, "couAddTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeIsNull() {
            addCriterion("cou_update_time is null");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeIsNotNull() {
            addCriterion("cou_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeEqualTo(Date value) {
            addCriterion("cou_update_time =", value, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeNotEqualTo(Date value) {
            addCriterion("cou_update_time <>", value, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeGreaterThan(Date value) {
            addCriterion("cou_update_time >", value, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cou_update_time >=", value, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeLessThan(Date value) {
            addCriterion("cou_update_time <", value, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("cou_update_time <=", value, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeIn(List<Date> values) {
            addCriterion("cou_update_time in", values, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeNotIn(List<Date> values) {
            addCriterion("cou_update_time not in", values, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("cou_update_time between", value1, value2, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("cou_update_time not between", value1, value2, "couUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCouDeletedIsNull() {
            addCriterion("cou_deleted is null");
            return (Criteria) this;
        }

        public Criteria andCouDeletedIsNotNull() {
            addCriterion("cou_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andCouDeletedEqualTo(Boolean value) {
            addCriterion("cou_deleted =", value, "couDeleted");
            return (Criteria) this;
        }

        public Criteria andCouDeletedNotEqualTo(Boolean value) {
            addCriterion("cou_deleted <>", value, "couDeleted");
            return (Criteria) this;
        }

        public Criteria andCouDeletedGreaterThan(Boolean value) {
            addCriterion("cou_deleted >", value, "couDeleted");
            return (Criteria) this;
        }

        public Criteria andCouDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("cou_deleted >=", value, "couDeleted");
            return (Criteria) this;
        }

        public Criteria andCouDeletedLessThan(Boolean value) {
            addCriterion("cou_deleted <", value, "couDeleted");
            return (Criteria) this;
        }

        public Criteria andCouDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("cou_deleted <=", value, "couDeleted");
            return (Criteria) this;
        }

        public Criteria andCouDeletedIn(List<Boolean> values) {
            addCriterion("cou_deleted in", values, "couDeleted");
            return (Criteria) this;
        }

        public Criteria andCouDeletedNotIn(List<Boolean> values) {
            addCriterion("cou_deleted not in", values, "couDeleted");
            return (Criteria) this;
        }

        public Criteria andCouDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("cou_deleted between", value1, value2, "couDeleted");
            return (Criteria) this;
        }

        public Criteria andCouDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("cou_deleted not between", value1, value2, "couDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_coupon
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private TicCouponExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria() {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public TicCouponExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andCouDeletedEqualTo(TicCoupon.IS_DELETED) : andCouDeletedNotEqualTo(TicCoupon.IS_DELETED);
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table litemall_coupon
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }
    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_coupon
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}