package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

import org.linlinjava.litemall.db.domain.LitemallComment.Column;

public class TicComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_id
     *
     * @mbggenerated
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_order_id
     *
     * @mbggenerated
     */
    private Integer comOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_content
     *
     * @mbggenerated
     */
    private String comContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_user_id
     *
     * @mbggenerated
     */
    private Integer comUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_has_picture
     *
     * @mbggenerated
     */
    private Boolean comHasPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_pic_urls
     *
     * @mbggenerated
     */
    private String[] comPicUrls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_like
     *
     * @mbggenerated
     */
    private Integer comLike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_star
     *
     * @mbggenerated
     */
    private Short comStar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_viewpoint
     *
     * @mbggenerated
     */
    private String comViewpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_isgood
     *
     * @mbggenerated
     */
    private Boolean comIsgood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_add_time
     *
     * @mbggenerated
     */
    private LocalDateTime comAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_update_time
     *
     * @mbggenerated
     */
    private LocalDateTime comUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_comment.com_deleted
     *
     * @mbggenerated
     */
    private Boolean comDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_id
     *
     * @return the value of tic_comment.com_id
     *
     * @mbggenerated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_id
     *
     * @param comId the value for tic_comment.com_id
     *
     * @mbggenerated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_order_id
     *
     * @return the value of tic_comment.com_order_id
     *
     * @mbggenerated
     */
    public Integer getComOrderId() {
        return comOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_order_id
     *
     * @param comOrderId the value for tic_comment.com_order_id
     *
     * @mbggenerated
     */
    public void setComOrderId(Integer comOrderId) {
        this.comOrderId = comOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_content
     *
     * @return the value of tic_comment.com_content
     *
     * @mbggenerated
     */
    public String getComContent() {
        return comContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_content
     *
     * @param comContent the value for tic_comment.com_content
     *
     * @mbggenerated
     */
    public void setComContent(String comContent) {
        this.comContent = comContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_user_id
     *
     * @return the value of tic_comment.com_user_id
     *
     * @mbggenerated
     */
    public Integer getComUserId() {
        return comUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_user_id
     *
     * @param comUserId the value for tic_comment.com_user_id
     *
     * @mbggenerated
     */
    public void setComUserId(Integer comUserId) {
        this.comUserId = comUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_has_picture
     *
     * @return the value of tic_comment.com_has_picture
     *
     * @mbggenerated
     */
    public Boolean getComHasPicture() {
        return comHasPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_has_picture
     *
     * @param comHasPicture the value for tic_comment.com_has_picture
     *
     * @mbggenerated
     */
    public void setComHasPicture(Boolean comHasPicture) {
        this.comHasPicture = comHasPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_pic_urls
     *
     * @return the value of tic_comment.com_pic_urls
     *
     * @mbggenerated
     */
    public String[] getComPicUrls() {
        return comPicUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_pic_urls
     *
     * @param comPicUrls the value for tic_comment.com_pic_urls
     *
     * @mbggenerated
     */
    public void setComPicUrls(String[] comPicUrls) {
        this.comPicUrls = comPicUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_like
     *
     * @return the value of tic_comment.com_like
     *
     * @mbggenerated
     */
    public Integer getComLike() {
        return comLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_like
     *
     * @param comLike the value for tic_comment.com_like
     *
     * @mbggenerated
     */
    public void setComLike(Integer comLike) {
        this.comLike = comLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_star
     *
     * @return the value of tic_comment.com_star
     *
     * @mbggenerated
     */
    public Short getComStar() {
        return comStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_star
     *
     * @param comStar the value for tic_comment.com_star
     *
     * @mbggenerated
     */
    public void setComStar(Short comStar) {
        this.comStar = comStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_viewpoint
     *
     * @return the value of tic_comment.com_viewpoint
     *
     * @mbggenerated
     */
    public String getComViewpoint() {
        return comViewpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_viewpoint
     *
     * @param comViewpoint the value for tic_comment.com_viewpoint
     *
     * @mbggenerated
     */
    public void setComViewpoint(String comViewpoint) {
        this.comViewpoint = comViewpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_isgood
     *
     * @return the value of tic_comment.com_isgood
     *
     * @mbggenerated
     */
    public Boolean getComIsgood() {
        return comIsgood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_isgood
     *
     * @param comIsgood the value for tic_comment.com_isgood
     *
     * @mbggenerated
     */
    public void setComIsgood(Boolean comIsgood) {
        this.comIsgood = comIsgood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_add_time
     *
     * @return the value of tic_comment.com_add_time
     *
     * @mbggenerated
     */
    public LocalDateTime getComAddTime() {
        return comAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_add_time
     *
     * @param comAddTime the value for tic_comment.com_add_time
     *
     * @mbggenerated
     */
    public void setComAddTime(LocalDateTime comAddTime) {
        this.comAddTime = comAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_update_time
     *
     * @return the value of tic_comment.com_update_time
     *
     * @mbggenerated
     */
    public LocalDateTime getComUpdateTime() {
        return comUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_update_time
     *
     * @param comUpdateTime the value for tic_comment.com_update_time
     *
     * @mbggenerated
     */
    public void setComUpdateTime(LocalDateTime comUpdateTime) {
        this.comUpdateTime = comUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_comment.com_deleted
     *
     * @return the value of tic_comment.com_deleted
     *
     * @mbggenerated
     */
    public Boolean getComDeleted() {
        return comDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_comment.com_deleted
     *
     * @param comDeleted the value for tic_comment.com_deleted
     *
     * @mbggenerated
     */
    public void setComDeleted(Boolean comDeleted) {
        this.comDeleted = comDeleted;
    }
    
    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
    	comId("com_id", "comId", "INTEGER", false),
    	comOrderId("com_orderId", "comOrderId", "INTEGER", false),
    	comContent("com_content", "comContent", "VARCHAR", true),
    	comUserId("com_userId", "comUserId", "INTEGER", false),
    	comHasPicture("com_hasPicture", "comHasPicture", "BIT", false),
    	comPicUrls("com_picUrls", "comPicUrls", "VARCHAR", false),
    	comLike("com_like", "comLike", "INTEGER", false),
    	comStar("com_star", "comStar", "SMALLINT", false),
    	comViewpoint("com_viewpoint", "comViewpoint", "VARCHAR", false),
    	comIsgood("com_isgood", "comIsgood", "BIT", false),
    	comAddTime("com_add_time", "comAddTime", "TIMESTAMP", false),
    	comUpdateTime("com_update_time", "comUpdateTime", "TIMESTAMP", false),
    	comDeleted("com_deleted", "comDeleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}