package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TicCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_id
     *
     * @mbggenerated
     */
    private Integer catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_name
     *
     * @mbggenerated
     */
    private String catName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_keywords
     *
     * @mbggenerated
     */
    private String catKeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_desc
     *
     * @mbggenerated
     */
    private String catDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_pic_url
     *
     * @mbggenerated
     */
    private String catPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_price
     *
     * @mbggenerated
     */
    private BigDecimal catPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_sort_order
     *
     * @mbggenerated
     */
    private Byte catSortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_is_on_sale
     *
     * @mbg.generated
     */
    private Integer catIsOnSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_view_id
     *
     * @mbg.generated
     */
    private Integer[] catViewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_isretreat
     *
     * @mbg.generated
     */
    private Integer catIsretreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_retre_day
     *
     * @mbg.generated
     */
    private Integer catRetreDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_retre_cost
     *
     * @mbg.generated
     */
    private BigDecimal catRetreCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_self_help
     *
     * @mbg.generated
     */
    private Integer catSelfHelp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_add_time
     *
     * @mbggenerated
     */
    private Date catAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_update_time
     *
     * @mbggenerated
     */
    private Date catUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_category.cat_deleted
     *
     * @mbggenerated
     */
    private Boolean catDeleted;

    private Integer catPeopleNum;

    public Integer getCatPeopleNum() {
        return catPeopleNum;
    }

    public void setCatPeopleNum(Integer catPeopleNum) {
        this.catPeopleNum = catPeopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_id
     *
     * @return the value of tic_category.cat_id
     *
     * @mbggenerated
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_id
     *
     * @param catId the value for tic_category.cat_id
     *
     * @mbggenerated
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_name
     *
     * @return the value of tic_category.cat_name
     *
     * @mbggenerated
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_name
     *
     * @param catName the value for tic_category.cat_name
     *
     * @mbggenerated
     */
    public void setCatName(String catName) {
        this.catName = catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_keywords
     *
     * @return the value of tic_category.cat_keywords
     *
     * @mbggenerated
     */
    public String getCatKeywords() {
        return catKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_keywords
     *
     * @param catKeywords the value for tic_category.cat_keywords
     *
     * @mbggenerated
     */
    public void setCatKeywords(String catKeywords) {
        this.catKeywords = catKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_desc
     *
     * @return the value of tic_category.cat_desc
     *
     * @mbggenerated
     */
    public String getCatDesc() {
        return catDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_desc
     *
     * @param catDesc the value for tic_category.cat_desc
     *
     * @mbggenerated
     */
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_pic_url
     *
     * @return the value of tic_category.cat_pic_url
     *
     * @mbggenerated
     */
    public String getCatPicUrl() {
        return catPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_pic_url
     *
     * @param catPicUrl the value for tic_category.cat_pic_url
     *
     * @mbggenerated
     */
    public void setCatPicUrl(String catPicUrl) {
        this.catPicUrl = catPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_price
     *
     * @return the value of tic_category.cat_price
     *
     * @mbggenerated
     */
    public BigDecimal getCatPrice() {
        return catPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_price
     *
     * @param catPrice the value for tic_category.cat_price
     *
     * @mbggenerated
     */
    public void setCatPrice(BigDecimal catPrice) {
        this.catPrice = catPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_sort_order
     *
     * @return the value of tic_category.cat_sort_order
     *
     * @mbggenerated
     */
    public Byte getCatSortOrder() {
        return catSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_sort_order
     *
     * @param catSortOrder the value for tic_category.cat_sort_order
     *
     * @mbggenerated
     */
    public void setCatSortOrder(Byte catSortOrder) {
        this.catSortOrder = catSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_is_on_sale
     *
     * @return the value of tic_category.cat_is_on_sale
     *
     * @mbg.generated
     */
    public Integer getCatIsOnSale() {
        return catIsOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_is_on_sale
     *
     * @param catIsOnSale the value for tic_category.cat_is_on_sale
     *
     * @mbg.generated
     */
    public void setCatIsOnSale(Integer catIsOnSale) {
        this.catIsOnSale = catIsOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_view_id
     *
     * @return the value of tic_category.cat_view_id
     *
     * @mbg.generated
     */
    public Integer[] getCatViewId() {
        return catViewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_view_id
     *
     * @param catViewId the value for tic_category.cat_view_id
     *
     * @mbg.generated
     */
    public void setCatViewId(Integer[] catViewId) {
        this.catViewId = catViewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_isretreat
     *
     * @return the value of tic_category.cat_isretreat
     *
     * @mbg.generated
     */
    public Integer getCatIsretreat() {
        return catIsretreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_isretreat
     *
     * @param catIsretreat the value for tic_category.cat_isretreat
     *
     * @mbg.generated
     */
    public void setCatIsretreat(Integer catIsretreat) {
        this.catIsretreat = catIsretreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_retre_day
     *
     * @return the value of tic_category.cat_retre_day
     *
     * @mbg.generated
     */
    public Integer getCatRetreDay() {
        return catRetreDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_retre_day
     *
     * @param catRetreDay the value for tic_category.cat_retre_day
     *
     * @mbg.generated
     */
    public void setCatRetreDay(Integer catRetreDay) {
        this.catRetreDay = catRetreDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_retre_cost
     *
     * @return the value of tic_category.cat_retre_cost
     *
     * @mbg.generated
     */
    public BigDecimal getCatRetreCost() {
        return catRetreCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_retre_cost
     *
     * @param catRetreCost the value for tic_category.cat_retre_cost
     *
     * @mbg.generated
     */
    public void setCatRetreCost(BigDecimal catRetreCost) {
        this.catRetreCost = catRetreCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_self_help
     *
     * @return the value of tic_category.cat_self_help
     *
     * @mbg.generated
     */
    public Integer getCatSelfHelp() {
        return catSelfHelp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_self_help
     *
     * @param catSelfHelp the value for tic_category.cat_self_help
     *
     * @mbg.generated
     */
    public void setCatSelfHelp(Integer catSelfHelp) {
        this.catSelfHelp = catSelfHelp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_add_time
     *
     * @return the value of tic_category.cat_add_time
     *
     * @mbggenerated
     */
    public Date getCatAddTime() {
        return catAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_add_time
     *
     * @param catAddTime the value for tic_category.cat_add_time
     *
     * @mbggenerated
     */
    public void setCatAddTime(Date catAddTime) {
        this.catAddTime = catAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_update_time
     *
     * @return the value of tic_category.cat_update_time
     *
     * @mbggenerated
     */
    public Date getCatUpdateTime() {
        return catUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_update_time
     *
     * @param catUpdateTime the value for tic_category.cat_update_time
     *
     * @mbggenerated
     */
    public void setCatUpdateTime(Date catUpdateTime) {
        this.catUpdateTime = catUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_category.cat_deleted
     *
     * @return the value of tic_category.cat_deleted
     *
     * @mbggenerated
     */
    public Boolean getCatDeleted() {
        return catDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_category.cat_deleted
     *
     * @param catDeleted the value for tic_category.cat_deleted
     *
     * @mbggenerated
     */
    public void setCatDeleted(Boolean catDeleted) {
        this.catDeleted = catDeleted;
    }
}