package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.linlinjava.litemall.db.domain.LitemallCoupon.Column;

public class TicCoupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_id
     *
     * @mbggenerated
     */
    private Integer couId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_name
     *
     * @mbggenerated
     */
    private String couName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_desc
     *
     * @mbggenerated
     */
    private String couDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_tag
     *
     * @mbggenerated
     */
    private String couTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_total
     *
     * @mbggenerated
     */
    private Integer couTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_get_count
     *
     * @mbggenerated
     */
    private Integer couGetCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_discount
     *
     * @mbggenerated
     */
    private BigDecimal couDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_min
     *
     * @mbggenerated
     */
    private BigDecimal couMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_limit
     *
     * @mbggenerated
     */
    private Short couLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_type
     *
     * @mbggenerated
     */
    private Short couType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_status
     *
     * @mbggenerated
     */
    private Short couStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_goods_type
     *
     * @mbggenerated
     */
    private Short couGoodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_goods_value
     *
     * @mbggenerated
     */
    private Integer[] couGoodsValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_code
     *
     * @mbggenerated
     */
    private String couCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_time_type
     *
     * @mbggenerated
     */
    private Short couTimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_days
     *
     * @mbggenerated
     */
    private Short couDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_start_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    private LocalDateTime couStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_end_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    private LocalDateTime couEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_add_time
     *
     * @mbggenerated
     */
    private LocalDateTime couAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_update_time
     *
     * @mbggenerated
     */
    private LocalDateTime couUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_coupon.cou_deleted
     *
     * @mbggenerated
     */
    private Boolean couDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_id
     *
     * @return the value of tic_coupon.cou_id
     *
     * @mbggenerated
     */
    public Integer getCouId() {
        return couId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_id
     *
     * @param couId the value for tic_coupon.cou_id
     *
     * @mbggenerated
     */
    public void setCouId(Integer couId) {
        this.couId = couId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_name
     *
     * @return the value of tic_coupon.cou_name
     *
     * @mbggenerated
     */
    public String getCouName() {
        return couName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_name
     *
     * @param couName the value for tic_coupon.cou_name
     *
     * @mbggenerated
     */
    public void setCouName(String couName) {
        this.couName = couName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_desc
     *
     * @return the value of tic_coupon.cou_desc
     *
     * @mbggenerated
     */
    public String getCouDesc() {
        return couDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_desc
     *
     * @param couDesc the value for tic_coupon.cou_desc
     *
     * @mbggenerated
     */
    public void setCouDesc(String couDesc) {
        this.couDesc = couDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_tag
     *
     * @return the value of tic_coupon.cou_tag
     *
     * @mbggenerated
     */
    public String getCouTag() {
        return couTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_tag
     *
     * @param couTag the value for tic_coupon.cou_tag
     *
     * @mbggenerated
     */
    public void setCouTag(String couTag) {
        this.couTag = couTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_total
     *
     * @return the value of tic_coupon.cou_total
     *
     * @mbggenerated
     */
    public Integer getCouTotal() {
        return couTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_total
     *
     * @param couTotal the value for tic_coupon.cou_total
     *
     * @mbggenerated
     */
    public void setCouTotal(Integer couTotal) {
        this.couTotal = couTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_get_count
     *
     * @return the value of tic_coupon.cou_get_count
     *
     * @mbggenerated
     */
    public Integer getCouGetCount() {
        return couGetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_get_count
     *
     * @param couGetCount the value for tic_coupon.cou_get_count
     *
     * @mbggenerated
     */
    public void setCouGetCount(Integer couGetCount) {
        this.couGetCount = couGetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_discount
     *
     * @return the value of tic_coupon.cou_discount
     *
     * @mbggenerated
     */
    public BigDecimal getCouDiscount() {
        return couDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_discount
     *
     * @param couDiscount the value for tic_coupon.cou_discount
     *
     * @mbggenerated
     */
    public void setCouDiscount(BigDecimal couDiscount) {
        this.couDiscount = couDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_min
     *
     * @return the value of tic_coupon.cou_min
     *
     * @mbggenerated
     */
    public BigDecimal getCouMin() {
        return couMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_min
     *
     * @param couMin the value for tic_coupon.cou_min
     *
     * @mbggenerated
     */
    public void setCouMin(BigDecimal couMin) {
        this.couMin = couMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_limit
     *
     * @return the value of tic_coupon.cou_limit
     *
     * @mbggenerated
     */
    public Short getCouLimit() {
        return couLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_limit
     *
     * @param couLimit the value for tic_coupon.cou_limit
     *
     * @mbggenerated
     */
    public void setCouLimit(Short couLimit) {
        this.couLimit = couLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_type
     *
     * @return the value of tic_coupon.cou_type
     *
     * @mbggenerated
     */
    public Short getCouType() {
        return couType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_type
     *
     * @param couType the value for tic_coupon.cou_type
     *
     * @mbggenerated
     */
    public void setCouType(Short couType) {
        this.couType = couType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_status
     *
     * @return the value of tic_coupon.cou_status
     *
     * @mbggenerated
     */
    public Short getCouStatus() {
        return couStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_status
     *
     * @param couStatus the value for tic_coupon.cou_status
     *
     * @mbggenerated
     */
    public void setCouStatus(Short couStatus) {
        this.couStatus = couStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_goods_type
     *
     * @return the value of tic_coupon.cou_goods_type
     *
     * @mbggenerated
     */
    public Short getCouGoodsType() {
        return couGoodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_goods_type
     *
     * @param couGoodsType the value for tic_coupon.cou_goods_type
     *
     * @mbggenerated
     */
    public void setCouGoodsType(Short couGoodsType) {
        this.couGoodsType = couGoodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_goods_value
     *
     * @return the value of tic_coupon.cou_goods_value
     *
     * @mbggenerated
     */
    public Integer[] getCouGoodsValue() {
        return couGoodsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_goods_value
     *
     * @param couGoodsValue the value for tic_coupon.cou_goods_value
     *
     * @mbggenerated
     */
    public void setCouGoodsValue(Integer[] couGoodsValue) {
        this.couGoodsValue = couGoodsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_code
     *
     * @return the value of tic_coupon.cou_code
     *
     * @mbggenerated
     */
    public String getCouCode() {
        return couCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_code
     *
     * @param couCode the value for tic_coupon.cou_code
     *
     * @mbggenerated
     */
    public void setCouCode(String couCode) {
        this.couCode = couCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_time_type
     *
     * @return the value of tic_coupon.cou_time_type
     *
     * @mbggenerated
     */
    public Short getCouTimeType() {
        return couTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_time_type
     *
     * @param couTimeType the value for tic_coupon.cou_time_type
     *
     * @mbggenerated
     */
    public void setCouTimeType(Short couTimeType) {
        this.couTimeType = couTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_days
     *
     * @return the value of tic_coupon.cou_days
     *
     * @mbggenerated
     */
    public Short getCouDays() {
        return couDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_days
     *
     * @param couDays the value for tic_coupon.cou_days
     *
     * @mbggenerated
     */
    public void setCouDays(Short couDays) {
        this.couDays = couDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_start_time
     *
     * @return the value of tic_coupon.cou_start_time
     *
     * @mbggenerated
     */
    public LocalDateTime getCouStartTime() {
        return couStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_start_time
     *
     * @param couStartTime the value for tic_coupon.cou_start_time
     *
     * @mbggenerated
     */
    public void setCouStartTime(LocalDateTime couStartTime) {
        this.couStartTime = couStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_end_time
     *
     * @return the value of tic_coupon.cou_end_time
     *
     * @mbggenerated
     */
    public LocalDateTime getCouEndTime() {
        return couEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_end_time
     *
     * @param couEndTime the value for tic_coupon.cou_end_time
     *
     * @mbggenerated
     */
    public void setCouEndTime(LocalDateTime couEndTime) {
        this.couEndTime = couEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_add_time
     *
     * @return the value of tic_coupon.cou_add_time
     *
     * @mbggenerated
     */
    public LocalDateTime getCouAddTime() {
        return couAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_add_time
     *
     * @param couAddTime the value for tic_coupon.cou_add_time
     *
     * @mbggenerated
     */
    public void setCouAddTime(LocalDateTime couAddTime) {
        this.couAddTime = couAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_update_time
     *
     * @return the value of tic_coupon.cou_update_time
     *
     * @mbggenerated
     */
    public LocalDateTime getCouUpdateTime() {
        return couUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_update_time
     *
     * @param couUpdateTime the value for tic_coupon.cou_update_time
     *
     * @mbggenerated
     */
    public void setCouUpdateTime(LocalDateTime couUpdateTime) {
        this.couUpdateTime = couUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_coupon.cou_deleted
     *
     * @return the value of tic_coupon.cou_deleted
     *
     * @mbggenerated
     */
    public Boolean getCouDeleted() {
        return couDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_coupon.cou_deleted
     *
     * @param couDeleted the value for tic_coupon.cou_deleted
     *
     * @mbggenerated
     */
    public void setCouDeleted(Boolean couDeleted) {
        this.couDeleted = couDeleted;
    }
    
    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        couId("cou_id", "couId", "INTEGER", false),
        couName("cou_name", "couName", "VARCHAR", true),
        couDesc("cou_desc", "couDesc", "VARCHAR", true),
        couTag("cou_tag", "couTag", "VARCHAR", false),
        couTotal("cou_total", "couTotal", "INTEGER", false),
        couGetCount("cou_get_count", "couGetCount", "INTEGER", false),
        couDiscount("cou_discount", "couDiscount", "DECIMAL", false),
        couMin("cou_min", "couMin", "DECIMAL", true),
        couLimit("cou_limit", "couLimit", "SMALLINT", true),
        couType("cou_type", "couType", "SMALLINT", true),
        couStatus("cou_status", "couStatus", "SMALLINT", true),
        couGoodsType("cou_goods_type", "couGoodsType", "SMALLINT", false),
        couGoodsValue("cou_goods_value", "couGoodsValue", "VARCHAR", false),
        couCode("cou_code", "couCode", "VARCHAR", false),
        couTimeType("cou_time_type", "couTimeType", "SMALLINT", false),
        couDays("cou_days", "couDays", "SMALLINT", true),
        couStartTime("cou_start_time", "couStartTime", "TIMESTAMP", false),
        couEndTime("cou_end_time", "couEndTime", "TIMESTAMP", false),
        couAddTime("cou_add_time", "couAddTime", "TIMESTAMP", false),
        couUpdateTime("cou_update_time", "couUpdateTime", "TIMESTAMP", false),
        couDeleted("cou_deleted", "couDeleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_coupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}