package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TicCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public TicCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> catViewIdCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            catViewIdCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getCatViewIdCriteria() {
            return catViewIdCriteria;
        }

        protected void addCatViewIdCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            catViewIdCriteria.add(new Criterion(condition, value, "org.linlinjava.litemall.db.mybatis.JsonIntegerArrayTypeHandler"));
            allCriteria = null;
        }

        protected void addCatViewIdCriterion(String condition, Integer[] value1, Integer[] value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            catViewIdCriteria.add(new Criterion(condition, value1, value2, "org.linlinjava.litemall.db.mybatis.JsonIntegerArrayTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || catViewIdCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(catViewIdCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andCatIdIsNull() {
            addCriterion("cat_id is null");
            return (Criteria) this;
        }

        public Criteria andCatIdIsNotNull() {
            addCriterion("cat_id is not null");
            return (Criteria) this;
        }

        public Criteria andCatIdEqualTo(Integer value) {
            addCriterion("cat_id =", value, "catId");
            return (Criteria) this;
        }

        public Criteria andCatIdNotEqualTo(Integer value) {
            addCriterion("cat_id <>", value, "catId");
            return (Criteria) this;
        }

        public Criteria andCatIdGreaterThan(Integer value) {
            addCriterion("cat_id >", value, "catId");
            return (Criteria) this;
        }

        public Criteria andCatIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cat_id >=", value, "catId");
            return (Criteria) this;
        }

        public Criteria andCatIdLessThan(Integer value) {
            addCriterion("cat_id <", value, "catId");
            return (Criteria) this;
        }

        public Criteria andCatIdLessThanOrEqualTo(Integer value) {
            addCriterion("cat_id <=", value, "catId");
            return (Criteria) this;
        }

        public Criteria andCatIdIn(List<Integer> values) {
            addCriterion("cat_id in", values, "catId");
            return (Criteria) this;
        }

        public Criteria andCatIdNotIn(List<Integer> values) {
            addCriterion("cat_id not in", values, "catId");
            return (Criteria) this;
        }

        public Criteria andCatIdBetween(Integer value1, Integer value2) {
            addCriterion("cat_id between", value1, value2, "catId");
            return (Criteria) this;
        }

        public Criteria andCatIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cat_id not between", value1, value2, "catId");
            return (Criteria) this;
        }

        public Criteria andCatNameIsNull() {
            addCriterion("cat_name is null");
            return (Criteria) this;
        }

        public Criteria andCatNameIsNotNull() {
            addCriterion("cat_name is not null");
            return (Criteria) this;
        }

        public Criteria andCatNameEqualTo(String value) {
            addCriterion("cat_name =", value, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameNotEqualTo(String value) {
            addCriterion("cat_name <>", value, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameGreaterThan(String value) {
            addCriterion("cat_name >", value, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameGreaterThanOrEqualTo(String value) {
            addCriterion("cat_name >=", value, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameLessThan(String value) {
            addCriterion("cat_name <", value, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameLessThanOrEqualTo(String value) {
            addCriterion("cat_name <=", value, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameLike(String value) {
            addCriterion("cat_name like", value, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameNotLike(String value) {
            addCriterion("cat_name not like", value, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameIn(List<String> values) {
            addCriterion("cat_name in", values, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameNotIn(List<String> values) {
            addCriterion("cat_name not in", values, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameBetween(String value1, String value2) {
            addCriterion("cat_name between", value1, value2, "catName");
            return (Criteria) this;
        }

        public Criteria andCatNameNotBetween(String value1, String value2) {
            addCriterion("cat_name not between", value1, value2, "catName");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsIsNull() {
            addCriterion("cat_keywords is null");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsIsNotNull() {
            addCriterion("cat_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsEqualTo(String value) {
            addCriterion("cat_keywords =", value, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsNotEqualTo(String value) {
            addCriterion("cat_keywords <>", value, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsGreaterThan(String value) {
            addCriterion("cat_keywords >", value, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("cat_keywords >=", value, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsLessThan(String value) {
            addCriterion("cat_keywords <", value, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsLessThanOrEqualTo(String value) {
            addCriterion("cat_keywords <=", value, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsLike(String value) {
            addCriterion("cat_keywords like", value, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsNotLike(String value) {
            addCriterion("cat_keywords not like", value, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsIn(List<String> values) {
            addCriterion("cat_keywords in", values, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsNotIn(List<String> values) {
            addCriterion("cat_keywords not in", values, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsBetween(String value1, String value2) {
            addCriterion("cat_keywords between", value1, value2, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatKeywordsNotBetween(String value1, String value2) {
            addCriterion("cat_keywords not between", value1, value2, "catKeywords");
            return (Criteria) this;
        }

        public Criteria andCatDescIsNull() {
            addCriterion("cat_desc is null");
            return (Criteria) this;
        }

        public Criteria andCatDescIsNotNull() {
            addCriterion("cat_desc is not null");
            return (Criteria) this;
        }

        public Criteria andCatDescEqualTo(String value) {
            addCriterion("cat_desc =", value, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescNotEqualTo(String value) {
            addCriterion("cat_desc <>", value, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescGreaterThan(String value) {
            addCriterion("cat_desc >", value, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescGreaterThanOrEqualTo(String value) {
            addCriterion("cat_desc >=", value, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescLessThan(String value) {
            addCriterion("cat_desc <", value, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescLessThanOrEqualTo(String value) {
            addCriterion("cat_desc <=", value, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescLike(String value) {
            addCriterion("cat_desc like", value, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescNotLike(String value) {
            addCriterion("cat_desc not like", value, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescIn(List<String> values) {
            addCriterion("cat_desc in", values, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescNotIn(List<String> values) {
            addCriterion("cat_desc not in", values, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescBetween(String value1, String value2) {
            addCriterion("cat_desc between", value1, value2, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatDescNotBetween(String value1, String value2) {
            addCriterion("cat_desc not between", value1, value2, "catDesc");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlIsNull() {
            addCriterion("cat_pic_url is null");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlIsNotNull() {
            addCriterion("cat_pic_url is not null");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlEqualTo(String value) {
            addCriterion("cat_pic_url =", value, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlNotEqualTo(String value) {
            addCriterion("cat_pic_url <>", value, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlGreaterThan(String value) {
            addCriterion("cat_pic_url >", value, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("cat_pic_url >=", value, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlLessThan(String value) {
            addCriterion("cat_pic_url <", value, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlLessThanOrEqualTo(String value) {
            addCriterion("cat_pic_url <=", value, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlLike(String value) {
            addCriterion("cat_pic_url like", value, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlNotLike(String value) {
            addCriterion("cat_pic_url not like", value, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlIn(List<String> values) {
            addCriterion("cat_pic_url in", values, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlNotIn(List<String> values) {
            addCriterion("cat_pic_url not in", values, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlBetween(String value1, String value2) {
            addCriterion("cat_pic_url between", value1, value2, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPicUrlNotBetween(String value1, String value2) {
            addCriterion("cat_pic_url not between", value1, value2, "catPicUrl");
            return (Criteria) this;
        }

        public Criteria andCatPriceIsNull() {
            addCriterion("cat_price is null");
            return (Criteria) this;
        }

        public Criteria andCatPriceIsNotNull() {
            addCriterion("cat_price is not null");
            return (Criteria) this;
        }

        public Criteria andCatPriceEqualTo(BigDecimal value) {
            addCriterion("cat_price =", value, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatPriceNotEqualTo(BigDecimal value) {
            addCriterion("cat_price <>", value, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatPriceGreaterThan(BigDecimal value) {
            addCriterion("cat_price >", value, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cat_price >=", value, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatPriceLessThan(BigDecimal value) {
            addCriterion("cat_price <", value, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cat_price <=", value, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatPriceIn(List<BigDecimal> values) {
            addCriterion("cat_price in", values, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatPriceNotIn(List<BigDecimal> values) {
            addCriterion("cat_price not in", values, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cat_price between", value1, value2, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cat_price not between", value1, value2, "catPrice");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderIsNull() {
            addCriterion("cat_sort_order is null");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderIsNotNull() {
            addCriterion("cat_sort_order is not null");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderEqualTo(Byte value) {
            addCriterion("cat_sort_order =", value, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderNotEqualTo(Byte value) {
            addCriterion("cat_sort_order <>", value, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderGreaterThan(Byte value) {
            addCriterion("cat_sort_order >", value, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderGreaterThanOrEqualTo(Byte value) {
            addCriterion("cat_sort_order >=", value, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderLessThan(Byte value) {
            addCriterion("cat_sort_order <", value, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderLessThanOrEqualTo(Byte value) {
            addCriterion("cat_sort_order <=", value, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderIn(List<Byte> values) {
            addCriterion("cat_sort_order in", values, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderNotIn(List<Byte> values) {
            addCriterion("cat_sort_order not in", values, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderBetween(Byte value1, Byte value2) {
            addCriterion("cat_sort_order between", value1, value2, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatSortOrderNotBetween(Byte value1, Byte value2) {
            addCriterion("cat_sort_order not between", value1, value2, "catSortOrder");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleIsNull() {
            addCriterion("cat_is_on_sale is null");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleIsNotNull() {
            addCriterion("cat_is_on_sale is not null");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleEqualTo(Integer value) {
            addCriterion("cat_is_on_sale =", value, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleNotEqualTo(Integer value) {
            addCriterion("cat_is_on_sale <>", value, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleGreaterThan(Integer value) {
            addCriterion("cat_is_on_sale >", value, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleGreaterThanOrEqualTo(Integer value) {
            addCriterion("cat_is_on_sale >=", value, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleLessThan(Integer value) {
            addCriterion("cat_is_on_sale <", value, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleLessThanOrEqualTo(Integer value) {
            addCriterion("cat_is_on_sale <=", value, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleIn(List<Integer> values) {
            addCriterion("cat_is_on_sale in", values, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleNotIn(List<Integer> values) {
            addCriterion("cat_is_on_sale not in", values, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleBetween(Integer value1, Integer value2) {
            addCriterion("cat_is_on_sale between", value1, value2, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatIsOnSaleNotBetween(Integer value1, Integer value2) {
            addCriterion("cat_is_on_sale not between", value1, value2, "catIsOnSale");
            return (Criteria) this;
        }

        public Criteria andCatViewIdIsNull() {
            addCriterion("cat_view_id is null");
            return (Criteria) this;
        }

        public Criteria andCatViewIdIsNotNull() {
            addCriterion("cat_view_id is not null");
            return (Criteria) this;
        }

        public Criteria andCatViewIdEqualTo(Integer[] value) {
            addCatViewIdCriterion("cat_view_id =", value, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdNotEqualTo(Integer[] value) {
            addCatViewIdCriterion("cat_view_id <>", value, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdGreaterThan(Integer[] value) {
            addCatViewIdCriterion("cat_view_id >", value, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdGreaterThanOrEqualTo(Integer[] value) {
            addCatViewIdCriterion("cat_view_id >=", value, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdLessThan(Integer[] value) {
            addCatViewIdCriterion("cat_view_id <", value, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdLessThanOrEqualTo(Integer[] value) {
            addCatViewIdCriterion("cat_view_id <=", value, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdLike(Integer[] value) {
            addCatViewIdCriterion("cat_view_id like", value, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdNotLike(Integer[] value) {
            addCatViewIdCriterion("cat_view_id not like", value, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdIn(List<Integer[]> values) {
            addCatViewIdCriterion("cat_view_id in", values, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdNotIn(List<Integer[]> values) {
            addCatViewIdCriterion("cat_view_id not in", values, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdBetween(Integer[] value1, Integer[] value2) {
            addCatViewIdCriterion("cat_view_id between", value1, value2, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatViewIdNotBetween(Integer[] value1, Integer[] value2) {
            addCatViewIdCriterion("cat_view_id not between", value1, value2, "catViewId");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatIsNull() {
            addCriterion("cat_isretreat is null");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatIsNotNull() {
            addCriterion("cat_isretreat is not null");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatEqualTo(Integer value) {
            addCriterion("cat_isretreat =", value, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatNotEqualTo(Integer value) {
            addCriterion("cat_isretreat <>", value, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatGreaterThan(Integer value) {
            addCriterion("cat_isretreat >", value, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatGreaterThanOrEqualTo(Integer value) {
            addCriterion("cat_isretreat >=", value, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatLessThan(Integer value) {
            addCriterion("cat_isretreat <", value, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatLessThanOrEqualTo(Integer value) {
            addCriterion("cat_isretreat <=", value, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatIn(List<Integer> values) {
            addCriterion("cat_isretreat in", values, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatNotIn(List<Integer> values) {
            addCriterion("cat_isretreat not in", values, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatBetween(Integer value1, Integer value2) {
            addCriterion("cat_isretreat between", value1, value2, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatIsretreatNotBetween(Integer value1, Integer value2) {
            addCriterion("cat_isretreat not between", value1, value2, "catIsretreat");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayIsNull() {
            addCriterion("cat_retre_day is null");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayIsNotNull() {
            addCriterion("cat_retre_day is not null");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayEqualTo(Integer value) {
            addCriterion("cat_retre_day =", value, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayNotEqualTo(Integer value) {
            addCriterion("cat_retre_day <>", value, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayGreaterThan(Integer value) {
            addCriterion("cat_retre_day >", value, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("cat_retre_day >=", value, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayLessThan(Integer value) {
            addCriterion("cat_retre_day <", value, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayLessThanOrEqualTo(Integer value) {
            addCriterion("cat_retre_day <=", value, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayIn(List<Integer> values) {
            addCriterion("cat_retre_day in", values, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayNotIn(List<Integer> values) {
            addCriterion("cat_retre_day not in", values, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayBetween(Integer value1, Integer value2) {
            addCriterion("cat_retre_day between", value1, value2, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreDayNotBetween(Integer value1, Integer value2) {
            addCriterion("cat_retre_day not between", value1, value2, "catRetreDay");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostIsNull() {
            addCriterion("cat_retre_cost is null");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostIsNotNull() {
            addCriterion("cat_retre_cost is not null");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostEqualTo(BigDecimal value) {
            addCriterion("cat_retre_cost =", value, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostNotEqualTo(BigDecimal value) {
            addCriterion("cat_retre_cost <>", value, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostGreaterThan(BigDecimal value) {
            addCriterion("cat_retre_cost >", value, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cat_retre_cost >=", value, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostLessThan(BigDecimal value) {
            addCriterion("cat_retre_cost <", value, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cat_retre_cost <=", value, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostIn(List<BigDecimal> values) {
            addCriterion("cat_retre_cost in", values, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostNotIn(List<BigDecimal> values) {
            addCriterion("cat_retre_cost not in", values, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cat_retre_cost between", value1, value2, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatRetreCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cat_retre_cost not between", value1, value2, "catRetreCost");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpIsNull() {
            addCriterion("cat_self_help is null");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpIsNotNull() {
            addCriterion("cat_self_help is not null");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpEqualTo(Integer value) {
            addCriterion("cat_self_help =", value, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpNotEqualTo(Integer value) {
            addCriterion("cat_self_help <>", value, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpGreaterThan(Integer value) {
            addCriterion("cat_self_help >", value, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpGreaterThanOrEqualTo(Integer value) {
            addCriterion("cat_self_help >=", value, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpLessThan(Integer value) {
            addCriterion("cat_self_help <", value, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpLessThanOrEqualTo(Integer value) {
            addCriterion("cat_self_help <=", value, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpIn(List<Integer> values) {
            addCriterion("cat_self_help in", values, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpNotIn(List<Integer> values) {
            addCriterion("cat_self_help not in", values, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpBetween(Integer value1, Integer value2) {
            addCriterion("cat_self_help between", value1, value2, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatSelfHelpNotBetween(Integer value1, Integer value2) {
            addCriterion("cat_self_help not between", value1, value2, "catSelfHelp");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeIsNull() {
            addCriterion("cat_add_time is null");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeIsNotNull() {
            addCriterion("cat_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeEqualTo(Date value) {
            addCriterion("cat_add_time =", value, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeNotEqualTo(Date value) {
            addCriterion("cat_add_time <>", value, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeGreaterThan(Date value) {
            addCriterion("cat_add_time >", value, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cat_add_time >=", value, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeLessThan(Date value) {
            addCriterion("cat_add_time <", value, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("cat_add_time <=", value, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeIn(List<Date> values) {
            addCriterion("cat_add_time in", values, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeNotIn(List<Date> values) {
            addCriterion("cat_add_time not in", values, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeBetween(Date value1, Date value2) {
            addCriterion("cat_add_time between", value1, value2, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("cat_add_time not between", value1, value2, "catAddTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeIsNull() {
            addCriterion("cat_update_time is null");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeIsNotNull() {
            addCriterion("cat_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeEqualTo(Date value) {
            addCriterion("cat_update_time =", value, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeNotEqualTo(Date value) {
            addCriterion("cat_update_time <>", value, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeGreaterThan(Date value) {
            addCriterion("cat_update_time >", value, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cat_update_time >=", value, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeLessThan(Date value) {
            addCriterion("cat_update_time <", value, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("cat_update_time <=", value, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeIn(List<Date> values) {
            addCriterion("cat_update_time in", values, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeNotIn(List<Date> values) {
            addCriterion("cat_update_time not in", values, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("cat_update_time between", value1, value2, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("cat_update_time not between", value1, value2, "catUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCatDeletedIsNull() {
            addCriterion("cat_deleted is null");
            return (Criteria) this;
        }

        public Criteria andCatDeletedIsNotNull() {
            addCriterion("cat_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andCatDeletedEqualTo(Boolean value) {
            addCriterion("cat_deleted =", value, "catDeleted");
            return (Criteria) this;
        }

        public Criteria andCatDeletedNotEqualTo(Boolean value) {
            addCriterion("cat_deleted <>", value, "catDeleted");
            return (Criteria) this;
        }

        public Criteria andCatDeletedGreaterThan(Boolean value) {
            addCriterion("cat_deleted >", value, "catDeleted");
            return (Criteria) this;
        }

        public Criteria andCatDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("cat_deleted >=", value, "catDeleted");
            return (Criteria) this;
        }

        public Criteria andCatDeletedLessThan(Boolean value) {
            addCriterion("cat_deleted <", value, "catDeleted");
            return (Criteria) this;
        }

        public Criteria andCatDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("cat_deleted <=", value, "catDeleted");
            return (Criteria) this;
        }

        public Criteria andCatDeletedIn(List<Boolean> values) {
            addCriterion("cat_deleted in", values, "catDeleted");
            return (Criteria) this;
        }

        public Criteria andCatDeletedNotIn(List<Boolean> values) {
            addCriterion("cat_deleted not in", values, "catDeleted");
            return (Criteria) this;
        }

        public Criteria andCatDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("cat_deleted between", value1, value2, "catDeleted");
            return (Criteria) this;
        }

        public Criteria andCatDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("cat_deleted not between", value1, value2, "catDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_category
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_category
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}