package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;

public class TicOrder extends LitemallAdmin{
    private String username;

    @Override
    public String getUsername(){return username;}

    @Override
    public void setUsername(String username) {
        this.username = username;
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_id
     *
     * @mbggenerated
     */
    private Integer ordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_user_id
     *
     * @mbggenerated
     */
    private Integer ordUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_order_sn
     *
     * @mbggenerated
     */
    private String ordOrderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_order_status
     *
     * @mbggenerated
     */
    private Short ordOrderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_tourist
     *
     * @mbggenerated
     */
    private String ordTourist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_mobile
     *
     * @mbggenerated
     */
    private String ordMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_ucard_id
     *
     * @mbggenerated
     */
    private String ordUcardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_goods_price
     *
     * @mbggenerated
     */
    private BigDecimal ordGoodsPrice;

    private Integer ordGoodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_coupon_id
     *
     * @mbggenerated
     */
    private Integer ordCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_coupon_price
     *
     * @mbggenerated
     */
    private BigDecimal ordCouponPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_order_price
     *
     * @mbggenerated
     */
    private BigDecimal ordOrderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_actual_price
     *
     * @mbggenerated
     */
    private BigDecimal ordActualPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_pay_id
     *
     * @mbggenerated
     */
    private String ordPayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_pay_time
     *
     * @mbggenerated
     */
    private LocalDateTime ordPayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_pay_way
     *
     * @mbggenerated
     */
    private Integer ordPayWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_admin_id
     *
     * @mbggenerated
     */
    private Integer ordAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_confirm_time
     *
     * @mbggenerated
     */
    private LocalDateTime ordConfirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_col_code
     *
     * @mbggenerated
     */
    private String ordColCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_qr_code
     *
     * @mbggenerated
     */
    private String ordQrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_end_time
     *
     * @mbggenerated
     */
    private LocalDateTime ordEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_detail
     *
     * @mbggenerated
     */
    private String ordDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_cat_id
     *
     * @mbg.generated
     */
    private Integer ordCatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_comment
     *
     * @mbg.generated
     */
    private Integer ordComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_add_time
     *
     * @mbggenerated
     */
    private LocalDateTime ordAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_update_time
     *
     * @mbggenerated
     */
    private LocalDateTime ordUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_deleted
     *
     * @mbggenerated
     */
    private Boolean ordDeleted;

    private String ordParkCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_order.ord_people_num
     *
     * @mbg.generated
     */
    private Integer ordPeopleNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_id
     *
     * @return the value of tic_order.ord_id
     *
     * @mbggenerated
     */
    public Integer getOrdId() {
        return ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_id
     *
     * @param ordId the value for tic_order.ord_id
     *
     * @mbggenerated
     */
    public void setOrdId(Integer ordId) {
        this.ordId = ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_user_id
     *
     * @return the value of tic_order.ord_user_id
     *
     * @mbggenerated
     */
    public Integer getOrdUserId() {
        return ordUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_user_id
     *
     * @param ordUserId the value for tic_order.ord_user_id
     *
     * @mbggenerated
     */
    public void setOrdUserId(Integer ordUserId) {
        this.ordUserId = ordUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_order_sn
     *
     * @return the value of tic_order.ord_order_sn
     *
     * @mbggenerated
     */
    public String getOrdOrderSn() {
        return ordOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_order_sn
     *
     * @param ordOrderSn the value for tic_order.ord_order_sn
     *
     * @mbggenerated
     */
    public void setOrdOrderSn(String ordOrderSn) {
        this.ordOrderSn = ordOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_order_status
     *
     * @return the value of tic_order.ord_order_status
     *
     * @mbggenerated
     */
    public Short getOrdOrderStatus() {
        return ordOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_order_status
     *
     * @param ordOrderStatus the value for tic_order.ord_order_status
     *
     * @mbggenerated
     */
    public void setOrdOrderStatus(Short ordOrderStatus) {
        this.ordOrderStatus = ordOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_tourist
     *
     * @return the value of tic_order.ord_tourist
     *
     * @mbggenerated
     */
    public String getOrdTourist() {
        return ordTourist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_tourist
     *
     * @param ordTourist the value for tic_order.ord_tourist
     *
     * @mbggenerated
     */
    public void setOrdTourist(String ordTourist) {
        this.ordTourist = ordTourist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_mobile
     *
     * @return the value of tic_order.ord_mobile
     *
     * @mbggenerated
     */
    public String getOrdMobile() {
        return ordMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_mobile
     *
     * @param ordMobile the value for tic_order.ord_mobile
     *
     * @mbggenerated
     */
    public void setOrdMobile(String ordMobile) {
        this.ordMobile = ordMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_ucard_id
     *
     * @return the value of tic_order.ord_ucard_id
     *
     * @mbggenerated
     */
    public String getOrdUcardId() {
        return ordUcardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_ucard_id
     *
     * @param ordUcardId the value for tic_order.ord_ucard_id
     *
     * @mbggenerated
     */
    public void setOrdUcardId(String ordUcardId) {
        this.ordUcardId = ordUcardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_goods_price
     *
     * @return the value of tic_order.ord_goods_price
     *
     * @mbggenerated
     */
    public BigDecimal getOrdGoodsPrice() {
        return ordGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_goods_price
     *
     * @param ordGoodsPrice the value for tic_order.ord_goods_price
     *
     * @mbggenerated
     */
    public void setOrdGoodsPrice(BigDecimal ordGoodsPrice) {
        this.ordGoodsPrice = ordGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_goods_num
     *
     * @return the value of tic_order.ord_goods_num
     *
     * @mbg.generated
     */
    public Integer getOrdGoodsNum() {
        return ordGoodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_goods_num
     *
     * @param ordGoodsNum the value for tic_order.ord_goods_num
     *
     * @mbg.generated
     */
    public void setOrdGoodsNum(Integer ordGoodsNum) {
        this.ordGoodsNum = ordGoodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_coupon_id
     *
     * @return the value of tic_order.ord_coupon_id
     *
     * @mbggenerated
     */
    public Integer getOrdCouponId() {
        return ordCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_coupon_id
     *
     * @param ordCouponId the value for tic_order.ord_coupon_id
     *
     * @mbggenerated
     */
    public void setOrdCouponId(Integer ordCouponId) {
        this.ordCouponId = ordCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_coupon_price
     *
     * @return the value of tic_order.ord_coupon_price
     *
     * @mbggenerated
     */
    public BigDecimal getOrdCouponPrice() {
        return ordCouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_coupon_price
     *
     * @param ordCouponPrice the value for tic_order.ord_coupon_price
     *
     * @mbggenerated
     */
    public void setOrdCouponPrice(BigDecimal ordCouponPrice) {
        this.ordCouponPrice = ordCouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_order_price
     *
     * @return the value of tic_order.ord_order_price
     *
     * @mbggenerated
     */
    public BigDecimal getOrdOrderPrice() {
        return ordOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_order_price
     *
     * @param ordOrderPrice the value for tic_order.ord_order_price
     *
     * @mbggenerated
     */
    public void setOrdOrderPrice(BigDecimal ordOrderPrice) {
        this.ordOrderPrice = ordOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_actual_price
     *
     * @return the value of tic_order.ord_actual_price
     *
     * @mbggenerated
     */
    public BigDecimal getOrdActualPrice() {
        return ordActualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_actual_price
     *
     * @param ordActualPrice the value for tic_order.ord_actual_price
     *
     * @mbggenerated
     */
    public void setOrdActualPrice(BigDecimal ordActualPrice) {
        this.ordActualPrice = ordActualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_pay_id
     *
     * @return the value of tic_order.ord_pay_id
     *
     * @mbggenerated
     */
    public String getOrdPayId() {
        return ordPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_pay_id
     *
     * @param ordPayId the value for tic_order.ord_pay_id
     *
     * @mbggenerated
     */
    public void setOrdPayId(String ordPayId) {
        this.ordPayId = ordPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_pay_time
     *
     * @return the value of tic_order.ord_pay_time
     *
     * @mbggenerated
     */
    public LocalDateTime getOrdPayTime() {
        return ordPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_pay_time
     *
     * @param ordPayTime the value for tic_order.ord_pay_time
     *
     * @mbggenerated
     */
    public void setOrdPayTime(LocalDateTime ordPayTime) {
        this.ordPayTime = ordPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_pay_way
     *
     * @return the value of tic_order.ord_pay_way
     *
     * @mbggenerated
     */
    public Integer getOrdPayWay() {
        return ordPayWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_pay_way
     *
     * @param ordPayWay the value for tic_order.ord_pay_way
     *
     * @mbggenerated
     */
    public void setOrdPayWay(Integer ordPayWay) {
        this.ordPayWay = ordPayWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_admin_id
     *
     * @return the value of tic_order.ord_admin_id
     *
     * @mbggenerated
     */
    public Integer getOrdAdminId() {
        return ordAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_admin_id
     *
     * @param ordAdminId the value for tic_order.ord_admin_id
     *
     * @mbggenerated
     */
    public void setOrdAdminId(Integer ordAdminId) {
        this.ordAdminId = ordAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_confirm_time
     *
     * @return the value of tic_order.ord_confirm_time
     *
     * @mbggenerated
     */
    public LocalDateTime getOrdConfirmTime() {
        return ordConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_confirm_time
     *
     * @param ordConfirmTime the value for tic_order.ord_confirm_time
     *
     * @mbggenerated
     */
    public void setOrdConfirmTime(LocalDateTime ordConfirmTime) {
        this.ordConfirmTime = ordConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_col_code
     *
     * @return the value of tic_order.ord_col_code
     *
     * @mbggenerated
     */
    public String getOrdColCode() {
        return ordColCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_col_code
     *
     * @param ordColCode the value for tic_order.ord_col_code
     *
     * @mbggenerated
     */
    public void setOrdColCode(String ordColCode) {
        this.ordColCode = ordColCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_qr_code
     *
     * @return the value of tic_order.ord_qr_code
     *
     * @mbggenerated
     */
    public String getOrdQrCode() {
        return ordQrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_qr_code
     *
     * @param ordQrCode the value for tic_order.ord_qr_code
     *
     * @mbggenerated
     */
    public void setOrdQrCode(String ordQrCode) {
        this.ordQrCode = ordQrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_end_time
     *
     * @return the value of tic_order.ord_end_time
     *
     * @mbggenerated
     */
    public LocalDateTime getOrdEndTime() {
        return ordEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_end_time
     *
     * @param ordEndTime the value for tic_order.ord_end_time
     *
     * @mbggenerated
     */
    public void setOrdEndTime(LocalDateTime ordEndTime) {
        this.ordEndTime = ordEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_detail
     *
     * @return the value of tic_order.ord_detail
     *
     * @mbggenerated
     */
    public String getOrdDetail() {
        return ordDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_detail
     *
     * @param ordDetail the value for tic_order.ord_detail
     *
     * @mbggenerated
     */
    public void setOrdDetail(String ordDetail) {
        this.ordDetail = ordDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_cat_id
     *
     * @return the value of tic_order.ord_cat_id
     *
     * @mbg.generated
     */
    public Integer getOrdCatId() {
        return ordCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_cat_id
     *
     * @param ordCatId the value for tic_order.ord_cat_id
     *
     * @mbg.generated
     */
    public void setOrdCatId(Integer ordCatId) {
        this.ordCatId = ordCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_comment
     *
     * @return the value of tic_order.ord_comment
     *
     * @mbg.generated
     */
    public Integer getOrdComment() {
        return ordComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_comment
     *
     * @param ordComment the value for tic_order.ord_comment
     *
     * @mbg.generated
     */
    public void setOrdComment(Integer ordComment) {
        this.ordComment = ordComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_add_time
     *
     * @return the value of tic_order.ord_add_time
     *
     * @mbggenerated
     */
    public LocalDateTime getOrdAddTime() {
        return ordAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_add_time
     *
     * @param ordAddTime the value for tic_order.ord_add_time
     *
     * @mbggenerated
     */
    public void setOrdAddTime(LocalDateTime ordAddTime) {
        this.ordAddTime = ordAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_update_time
     *
     * @return the value of tic_order.ord_update_time
     *
     * @mbggenerated
     */
    public LocalDateTime getOrdUpdateTime() {
        return ordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_update_time
     *
     * @param ordUpdateTime the value for tic_order.ord_update_time
     *
     * @mbggenerated
     */
    public void setOrdUpdateTime(LocalDateTime ordUpdateTime) {
        this.ordUpdateTime = ordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_deleted
     *
     * @return the value of tic_order.ord_deleted
     *
     * @mbggenerated
     */
    public Boolean getOrdDeleted() {
        return ordDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_deleted
     *
     * @param ordDeleted the value for tic_order.ord_deleted
     *
     * @mbggenerated
     */
    public void setOrdDeleted(Boolean ordDeleted) {
        this.ordDeleted = ordDeleted;
    }
    public String getOrdParkCode() {
        return ordParkCode;
    }
    public void setOrdParkCode(String ordParkCode) {
        this.ordParkCode = ordParkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_order.ord_people_num
     *
     * @return the value of tic_order.ord_people_num
     *
     * @mbg.generated
     */
    public Integer getOrdPeopleNum() {
        return ordPeopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_order.ord_people_num
     *
     * @param ordPeopleNum the value for tic_order.ord_people_num
     *
     * @mbg.generated
     */
    public void setOrdPeopleNum(Integer ordPeopleNum) {
        this.ordPeopleNum = ordPeopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ordId=").append(ordId);
        sb.append(", ordUserId=").append(ordUserId);
        sb.append(", ordOrderSn=").append(ordOrderSn);
        sb.append(", ordOrderStatus=").append(ordOrderStatus);
        sb.append(", ordTourist=").append(ordTourist);
        sb.append(", ordMobile=").append(ordMobile);
        sb.append(", ordUcardId=").append(ordUcardId);
        sb.append(", ordGoodsPrice=").append(ordGoodsPrice);
        sb.append(", ordGoodsNum=").append(ordGoodsNum);
        sb.append(", ordCouponId=").append(ordCouponId);
        sb.append(", ordCouponPrice=").append(ordCouponPrice);
        sb.append(", ordOrderPrice=").append(ordOrderPrice);
        sb.append(", ordActualPrice=").append(ordActualPrice);
        sb.append(", ordPayId=").append(ordPayId);
        sb.append(", ordPayTime=").append(ordPayTime);
        sb.append(", ordPayWay=").append(ordPayWay);
        sb.append(", ordAdminId=").append(ordAdminId);
        sb.append(", ordConfirmTime=").append(ordConfirmTime);
        sb.append(", ordColCode=").append(ordColCode);
        sb.append(", ordQrCode=").append(ordQrCode);
        sb.append(", ordEndTime=").append(ordEndTime);
        sb.append(", ordDetail=").append(ordDetail);
        sb.append(", ordCatId=").append(ordCatId);
        sb.append(", ordComment=").append(ordComment);
        sb.append(", ordAddTime=").append(ordAddTime);
        sb.append(", ordUpdateTime=").append(ordUpdateTime);
        sb.append(", ordDeleted=").append(ordDeleted);
        sb.append(", ordParkCode=").append(ordParkCode);
        sb.append(", ordPeopleNum=").append(ordPeopleNum);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TicOrder other = (TicOrder) that;
        return (this.getOrdId() == null ? other.getOrdId() == null : this.getOrdId().equals(other.getOrdId()))
            && (this.getOrdUserId() == null ? other.getOrdUserId() == null : this.getOrdUserId().equals(other.getOrdUserId()))
            && (this.getOrdOrderSn() == null ? other.getOrdOrderSn() == null : this.getOrdOrderSn().equals(other.getOrdOrderSn()))
            && (this.getOrdOrderStatus() == null ? other.getOrdOrderStatus() == null : this.getOrdOrderStatus().equals(other.getOrdOrderStatus()))
            && (this.getOrdTourist() == null ? other.getOrdTourist() == null : this.getOrdTourist().equals(other.getOrdTourist()))
            && (this.getOrdMobile() == null ? other.getOrdMobile() == null : this.getOrdMobile().equals(other.getOrdMobile()))
            && (this.getOrdUcardId() == null ? other.getOrdUcardId() == null : this.getOrdUcardId().equals(other.getOrdUcardId()))
            && (this.getOrdGoodsPrice() == null ? other.getOrdGoodsPrice() == null : this.getOrdGoodsPrice().equals(other.getOrdGoodsPrice()))
            && (this.getOrdGoodsNum() == null ? other.getOrdGoodsNum() == null : this.getOrdGoodsNum().equals(other.getOrdGoodsNum()))
            && (this.getOrdCouponId() == null ? other.getOrdCouponId() == null : this.getOrdCouponId().equals(other.getOrdCouponId()))
            && (this.getOrdCouponPrice() == null ? other.getOrdCouponPrice() == null : this.getOrdCouponPrice().equals(other.getOrdCouponPrice()))
            && (this.getOrdOrderPrice() == null ? other.getOrdOrderPrice() == null : this.getOrdOrderPrice().equals(other.getOrdOrderPrice()))
            && (this.getOrdActualPrice() == null ? other.getOrdActualPrice() == null : this.getOrdActualPrice().equals(other.getOrdActualPrice()))
            && (this.getOrdPayId() == null ? other.getOrdPayId() == null : this.getOrdPayId().equals(other.getOrdPayId()))
            && (this.getOrdPayTime() == null ? other.getOrdPayTime() == null : this.getOrdPayTime().equals(other.getOrdPayTime()))
            && (this.getOrdPayWay() == null ? other.getOrdPayWay() == null : this.getOrdPayWay().equals(other.getOrdPayWay()))
            && (this.getOrdAdminId() == null ? other.getOrdAdminId() == null : this.getOrdAdminId().equals(other.getOrdAdminId()))
            && (this.getOrdConfirmTime() == null ? other.getOrdConfirmTime() == null : this.getOrdConfirmTime().equals(other.getOrdConfirmTime()))
            && (this.getOrdColCode() == null ? other.getOrdColCode() == null : this.getOrdColCode().equals(other.getOrdColCode()))
            && (this.getOrdQrCode() == null ? other.getOrdQrCode() == null : this.getOrdQrCode().equals(other.getOrdQrCode()))
            && (this.getOrdEndTime() == null ? other.getOrdEndTime() == null : this.getOrdEndTime().equals(other.getOrdEndTime()))
            && (this.getOrdDetail() == null ? other.getOrdDetail() == null : this.getOrdDetail().equals(other.getOrdDetail()))
            && (this.getOrdCatId() == null ? other.getOrdCatId() == null : this.getOrdCatId().equals(other.getOrdCatId()))
            && (this.getOrdComment() == null ? other.getOrdComment() == null : this.getOrdComment().equals(other.getOrdComment()))
            && (this.getOrdAddTime() == null ? other.getOrdAddTime() == null : this.getOrdAddTime().equals(other.getOrdAddTime()))
            && (this.getOrdUpdateTime() == null ? other.getOrdUpdateTime() == null : this.getOrdUpdateTime().equals(other.getOrdUpdateTime()))
            && (this.getOrdDeleted() == null ? other.getOrdDeleted() == null : this.getOrdDeleted().equals(other.getOrdDeleted()))
            && (this.getOrdParkCode() == null ? other.getOrdParkCode() == null : this.getOrdParkCode().equals(other.getOrdParkCode()))
            && (this.getOrdPeopleNum() == null ? other.getOrdPeopleNum() == null : this.getOrdPeopleNum().equals(other.getOrdPeopleNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_order
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrdId() == null) ? 0 : getOrdId().hashCode());
        result = prime * result + ((getOrdUserId() == null) ? 0 : getOrdUserId().hashCode());
        result = prime * result + ((getOrdOrderSn() == null) ? 0 : getOrdOrderSn().hashCode());
        result = prime * result + ((getOrdOrderStatus() == null) ? 0 : getOrdOrderStatus().hashCode());
        result = prime * result + ((getOrdTourist() == null) ? 0 : getOrdTourist().hashCode());
        result = prime * result + ((getOrdMobile() == null) ? 0 : getOrdMobile().hashCode());
        result = prime * result + ((getOrdUcardId() == null) ? 0 : getOrdUcardId().hashCode());
        result = prime * result + ((getOrdGoodsPrice() == null) ? 0 : getOrdGoodsPrice().hashCode());
        result = prime * result + ((getOrdGoodsNum() == null) ? 0 : getOrdGoodsNum().hashCode());
        result = prime * result + ((getOrdCouponId() == null) ? 0 : getOrdCouponId().hashCode());
        result = prime * result + ((getOrdCouponPrice() == null) ? 0 : getOrdCouponPrice().hashCode());
        result = prime * result + ((getOrdOrderPrice() == null) ? 0 : getOrdOrderPrice().hashCode());
        result = prime * result + ((getOrdActualPrice() == null) ? 0 : getOrdActualPrice().hashCode());
        result = prime * result + ((getOrdPayId() == null) ? 0 : getOrdPayId().hashCode());
        result = prime * result + ((getOrdPayTime() == null) ? 0 : getOrdPayTime().hashCode());
        result = prime * result + ((getOrdPayWay() == null) ? 0 : getOrdPayWay().hashCode());
        result = prime * result + ((getOrdAdminId() == null) ? 0 : getOrdAdminId().hashCode());
        result = prime * result + ((getOrdConfirmTime() == null) ? 0 : getOrdConfirmTime().hashCode());
        result = prime * result + ((getOrdColCode() == null) ? 0 : getOrdColCode().hashCode());
        result = prime * result + ((getOrdQrCode() == null) ? 0 : getOrdQrCode().hashCode());
        result = prime * result + ((getOrdEndTime() == null) ? 0 : getOrdEndTime().hashCode());
        result = prime * result + ((getOrdDetail() == null) ? 0 : getOrdDetail().hashCode());
        result = prime * result + ((getOrdCatId() == null) ? 0 : getOrdCatId().hashCode());
        result = prime * result + ((getOrdComment() == null) ? 0 : getOrdComment().hashCode());
        result = prime * result + ((getOrdAddTime() == null) ? 0 : getOrdAddTime().hashCode());
        result = prime * result + ((getOrdUpdateTime() == null) ? 0 : getOrdUpdateTime().hashCode());
        result = prime * result + ((getOrdDeleted() == null) ? 0 : getOrdDeleted().hashCode());
        result = prime * result + ((getOrdParkCode() == null) ? 0 : getOrdParkCode().hashCode());
        result = prime * result + ((getOrdPeopleNum() == null) ? 0 : getOrdPeopleNum().hashCode());
        return result;
    }
}