package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TicRefRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ref_rule.ref_id
     *
     * @mbggenerated
     */
    private Integer refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ref_rule.ref_name
     *
     * @mbggenerated
     */
    private String refName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ref_rule.ref_day
     *
     * @mbggenerated
     */
    private Integer refDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ref_rule.ref_rate
     *
     * @mbggenerated
     */
    private BigDecimal refRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ref_rule.ref_end_reftime
     *
     * @mbggenerated
     */
    private Integer refEndReftime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ref_rule.ref_free_time
     *
     * @mbggenerated
     */
    private Integer refFreeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ref_rule.ref_add_time
     *
     * @mbggenerated
     */
    private Date refAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ref_rule.ref_update_time
     *
     * @mbggenerated
     */
    private Date refUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_ref_rule.ref_delete
     *
     * @mbggenerated
     */
    private Boolean refDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ref_rule.ref_id
     *
     * @return the value of tic_ref_rule.ref_id
     *
     * @mbggenerated
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ref_rule.ref_id
     *
     * @param refId the value for tic_ref_rule.ref_id
     *
     * @mbggenerated
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ref_rule.ref_name
     *
     * @return the value of tic_ref_rule.ref_name
     *
     * @mbggenerated
     */
    public String getRefName() {
        return refName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ref_rule.ref_name
     *
     * @param refName the value for tic_ref_rule.ref_name
     *
     * @mbggenerated
     */
    public void setRefName(String refName) {
        this.refName = refName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ref_rule.ref_day
     *
     * @return the value of tic_ref_rule.ref_day
     *
     * @mbggenerated
     */
    public Integer getRefDay() {
        return refDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ref_rule.ref_day
     *
     * @param refDay the value for tic_ref_rule.ref_day
     *
     * @mbggenerated
     */
    public void setRefDay(Integer refDay) {
        this.refDay = refDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ref_rule.ref_rate
     *
     * @return the value of tic_ref_rule.ref_rate
     *
     * @mbggenerated
     */
    public BigDecimal getRefRate() {
        return refRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ref_rule.ref_rate
     *
     * @param refRate the value for tic_ref_rule.ref_rate
     *
     * @mbggenerated
     */
    public void setRefRate(BigDecimal refRate) {
        this.refRate = refRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ref_rule.ref_end_reftime
     *
     * @return the value of tic_ref_rule.ref_end_reftime
     *
     * @mbggenerated
     */
    public Integer getRefEndReftime() {
        return refEndReftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ref_rule.ref_end_reftime
     *
     * @param refEndReftime the value for tic_ref_rule.ref_end_reftime
     *
     * @mbggenerated
     */
    public void setRefEndReftime(Integer refEndReftime) {
        this.refEndReftime = refEndReftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ref_rule.ref_free_time
     *
     * @return the value of tic_ref_rule.ref_free_time
     *
     * @mbggenerated
     */
    public Integer getRefFreeTime() {
        return refFreeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ref_rule.ref_free_time
     *
     * @param refFreeTime the value for tic_ref_rule.ref_free_time
     *
     * @mbggenerated
     */
    public void setRefFreeTime(Integer refFreeTime) {
        this.refFreeTime = refFreeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ref_rule.ref_add_time
     *
     * @return the value of tic_ref_rule.ref_add_time
     *
     * @mbggenerated
     */
    public Date getRefAddTime() {
        return refAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ref_rule.ref_add_time
     *
     * @param refAddTime the value for tic_ref_rule.ref_add_time
     *
     * @mbggenerated
     */
    public void setRefAddTime(Date refAddTime) {
        this.refAddTime = refAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ref_rule.ref_update_time
     *
     * @return the value of tic_ref_rule.ref_update_time
     *
     * @mbggenerated
     */
    public Date getRefUpdateTime() {
        return refUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ref_rule.ref_update_time
     *
     * @param refUpdateTime the value for tic_ref_rule.ref_update_time
     *
     * @mbggenerated
     */
    public void setRefUpdateTime(Date refUpdateTime) {
        this.refUpdateTime = refUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_ref_rule.ref_delete
     *
     * @return the value of tic_ref_rule.ref_delete
     *
     * @mbggenerated
     */
    public Boolean getRefDelete() {
        return refDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_ref_rule.ref_delete
     *
     * @param refDelete the value for tic_ref_rule.ref_delete
     *
     * @mbggenerated
     */
    public void setRefDelete(Boolean refDelete) {
        this.refDelete = refDelete;
    }
}