package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TicRefRuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public TicRefRuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRefIdIsNull() {
            addCriterion("ref_id is null");
            return (Criteria) this;
        }

        public Criteria andRefIdIsNotNull() {
            addCriterion("ref_id is not null");
            return (Criteria) this;
        }

        public Criteria andRefIdEqualTo(Integer value) {
            addCriterion("ref_id =", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotEqualTo(Integer value) {
            addCriterion("ref_id <>", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdGreaterThan(Integer value) {
            addCriterion("ref_id >", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ref_id >=", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdLessThan(Integer value) {
            addCriterion("ref_id <", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdLessThanOrEqualTo(Integer value) {
            addCriterion("ref_id <=", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdIn(List<Integer> values) {
            addCriterion("ref_id in", values, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotIn(List<Integer> values) {
            addCriterion("ref_id not in", values, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdBetween(Integer value1, Integer value2) {
            addCriterion("ref_id between", value1, value2, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ref_id not between", value1, value2, "refId");
            return (Criteria) this;
        }

        public Criteria andRefNameIsNull() {
            addCriterion("ref_name is null");
            return (Criteria) this;
        }

        public Criteria andRefNameIsNotNull() {
            addCriterion("ref_name is not null");
            return (Criteria) this;
        }

        public Criteria andRefNameEqualTo(String value) {
            addCriterion("ref_name =", value, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameNotEqualTo(String value) {
            addCriterion("ref_name <>", value, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameGreaterThan(String value) {
            addCriterion("ref_name >", value, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameGreaterThanOrEqualTo(String value) {
            addCriterion("ref_name >=", value, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameLessThan(String value) {
            addCriterion("ref_name <", value, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameLessThanOrEqualTo(String value) {
            addCriterion("ref_name <=", value, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameLike(String value) {
            addCriterion("ref_name like", value, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameNotLike(String value) {
            addCriterion("ref_name not like", value, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameIn(List<String> values) {
            addCriterion("ref_name in", values, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameNotIn(List<String> values) {
            addCriterion("ref_name not in", values, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameBetween(String value1, String value2) {
            addCriterion("ref_name between", value1, value2, "refName");
            return (Criteria) this;
        }

        public Criteria andRefNameNotBetween(String value1, String value2) {
            addCriterion("ref_name not between", value1, value2, "refName");
            return (Criteria) this;
        }

        public Criteria andRefDayIsNull() {
            addCriterion("ref_day is null");
            return (Criteria) this;
        }

        public Criteria andRefDayIsNotNull() {
            addCriterion("ref_day is not null");
            return (Criteria) this;
        }

        public Criteria andRefDayEqualTo(Integer value) {
            addCriterion("ref_day =", value, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefDayNotEqualTo(Integer value) {
            addCriterion("ref_day <>", value, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefDayGreaterThan(Integer value) {
            addCriterion("ref_day >", value, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("ref_day >=", value, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefDayLessThan(Integer value) {
            addCriterion("ref_day <", value, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefDayLessThanOrEqualTo(Integer value) {
            addCriterion("ref_day <=", value, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefDayIn(List<Integer> values) {
            addCriterion("ref_day in", values, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefDayNotIn(List<Integer> values) {
            addCriterion("ref_day not in", values, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefDayBetween(Integer value1, Integer value2) {
            addCriterion("ref_day between", value1, value2, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefDayNotBetween(Integer value1, Integer value2) {
            addCriterion("ref_day not between", value1, value2, "refDay");
            return (Criteria) this;
        }

        public Criteria andRefRateIsNull() {
            addCriterion("ref_rate is null");
            return (Criteria) this;
        }

        public Criteria andRefRateIsNotNull() {
            addCriterion("ref_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRefRateEqualTo(BigDecimal value) {
            addCriterion("ref_rate =", value, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefRateNotEqualTo(BigDecimal value) {
            addCriterion("ref_rate <>", value, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefRateGreaterThan(BigDecimal value) {
            addCriterion("ref_rate >", value, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ref_rate >=", value, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefRateLessThan(BigDecimal value) {
            addCriterion("ref_rate <", value, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ref_rate <=", value, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefRateIn(List<BigDecimal> values) {
            addCriterion("ref_rate in", values, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefRateNotIn(List<BigDecimal> values) {
            addCriterion("ref_rate not in", values, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ref_rate between", value1, value2, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ref_rate not between", value1, value2, "refRate");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeIsNull() {
            addCriterion("ref_end_reftime is null");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeIsNotNull() {
            addCriterion("ref_end_reftime is not null");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeEqualTo(Integer value) {
            addCriterion("ref_end_reftime =", value, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeNotEqualTo(Integer value) {
            addCriterion("ref_end_reftime <>", value, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeGreaterThan(Integer value) {
            addCriterion("ref_end_reftime >", value, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ref_end_reftime >=", value, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeLessThan(Integer value) {
            addCriterion("ref_end_reftime <", value, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeLessThanOrEqualTo(Integer value) {
            addCriterion("ref_end_reftime <=", value, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeIn(List<Integer> values) {
            addCriterion("ref_end_reftime in", values, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeNotIn(List<Integer> values) {
            addCriterion("ref_end_reftime not in", values, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeBetween(Integer value1, Integer value2) {
            addCriterion("ref_end_reftime between", value1, value2, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefEndReftimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ref_end_reftime not between", value1, value2, "refEndReftime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeIsNull() {
            addCriterion("ref_free_time is null");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeIsNotNull() {
            addCriterion("ref_free_time is not null");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeEqualTo(Integer value) {
            addCriterion("ref_free_time =", value, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeNotEqualTo(Integer value) {
            addCriterion("ref_free_time <>", value, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeGreaterThan(Integer value) {
            addCriterion("ref_free_time >", value, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ref_free_time >=", value, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeLessThan(Integer value) {
            addCriterion("ref_free_time <", value, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeLessThanOrEqualTo(Integer value) {
            addCriterion("ref_free_time <=", value, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeIn(List<Integer> values) {
            addCriterion("ref_free_time in", values, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeNotIn(List<Integer> values) {
            addCriterion("ref_free_time not in", values, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeBetween(Integer value1, Integer value2) {
            addCriterion("ref_free_time between", value1, value2, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefFreeTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ref_free_time not between", value1, value2, "refFreeTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeIsNull() {
            addCriterion("ref_add_time is null");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeIsNotNull() {
            addCriterion("ref_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeEqualTo(Date value) {
            addCriterion("ref_add_time =", value, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeNotEqualTo(Date value) {
            addCriterion("ref_add_time <>", value, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeGreaterThan(Date value) {
            addCriterion("ref_add_time >", value, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ref_add_time >=", value, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeLessThan(Date value) {
            addCriterion("ref_add_time <", value, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ref_add_time <=", value, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeIn(List<Date> values) {
            addCriterion("ref_add_time in", values, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeNotIn(List<Date> values) {
            addCriterion("ref_add_time not in", values, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeBetween(Date value1, Date value2) {
            addCriterion("ref_add_time between", value1, value2, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ref_add_time not between", value1, value2, "refAddTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeIsNull() {
            addCriterion("ref_update_time is null");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeIsNotNull() {
            addCriterion("ref_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeEqualTo(Date value) {
            addCriterion("ref_update_time =", value, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeNotEqualTo(Date value) {
            addCriterion("ref_update_time <>", value, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeGreaterThan(Date value) {
            addCriterion("ref_update_time >", value, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ref_update_time >=", value, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeLessThan(Date value) {
            addCriterion("ref_update_time <", value, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("ref_update_time <=", value, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeIn(List<Date> values) {
            addCriterion("ref_update_time in", values, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeNotIn(List<Date> values) {
            addCriterion("ref_update_time not in", values, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("ref_update_time between", value1, value2, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("ref_update_time not between", value1, value2, "refUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRefDeleteIsNull() {
            addCriterion("ref_delete is null");
            return (Criteria) this;
        }

        public Criteria andRefDeleteIsNotNull() {
            addCriterion("ref_delete is not null");
            return (Criteria) this;
        }

        public Criteria andRefDeleteEqualTo(Boolean value) {
            addCriterion("ref_delete =", value, "refDelete");
            return (Criteria) this;
        }

        public Criteria andRefDeleteNotEqualTo(Boolean value) {
            addCriterion("ref_delete <>", value, "refDelete");
            return (Criteria) this;
        }

        public Criteria andRefDeleteGreaterThan(Boolean value) {
            addCriterion("ref_delete >", value, "refDelete");
            return (Criteria) this;
        }

        public Criteria andRefDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ref_delete >=", value, "refDelete");
            return (Criteria) this;
        }

        public Criteria andRefDeleteLessThan(Boolean value) {
            addCriterion("ref_delete <", value, "refDelete");
            return (Criteria) this;
        }

        public Criteria andRefDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("ref_delete <=", value, "refDelete");
            return (Criteria) this;
        }

        public Criteria andRefDeleteIn(List<Boolean> values) {
            addCriterion("ref_delete in", values, "refDelete");
            return (Criteria) this;
        }

        public Criteria andRefDeleteNotIn(List<Boolean> values) {
            addCriterion("ref_delete not in", values, "refDelete");
            return (Criteria) this;
        }

        public Criteria andRefDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("ref_delete between", value1, value2, "refDelete");
            return (Criteria) this;
        }

        public Criteria andRefDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ref_delete not between", value1, value2, "refDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_ref_rule
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_ref_rule
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}