package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TicSystemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public TicSystemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysIdIsNull() {
            addCriterion("sys_id is null");
            return (Criteria) this;
        }

        public Criteria andSysIdIsNotNull() {
            addCriterion("sys_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysIdEqualTo(Integer value) {
            addCriterion("sys_id =", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotEqualTo(Integer value) {
            addCriterion("sys_id <>", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThan(Integer value) {
            addCriterion("sys_id >", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_id >=", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLessThan(Integer value) {
            addCriterion("sys_id <", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLessThanOrEqualTo(Integer value) {
            addCriterion("sys_id <=", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdIn(List<Integer> values) {
            addCriterion("sys_id in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotIn(List<Integer> values) {
            addCriterion("sys_id not in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdBetween(Integer value1, Integer value2) {
            addCriterion("sys_id between", value1, value2, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_id not between", value1, value2, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameIsNull() {
            addCriterion("sys_key_name is null");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameIsNotNull() {
            addCriterion("sys_key_name is not null");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameEqualTo(String value) {
            addCriterion("sys_key_name =", value, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameNotEqualTo(String value) {
            addCriterion("sys_key_name <>", value, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameGreaterThan(String value) {
            addCriterion("sys_key_name >", value, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameGreaterThanOrEqualTo(String value) {
            addCriterion("sys_key_name >=", value, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameLessThan(String value) {
            addCriterion("sys_key_name <", value, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameLessThanOrEqualTo(String value) {
            addCriterion("sys_key_name <=", value, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameLike(String value) {
            addCriterion("sys_key_name like", value, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameNotLike(String value) {
            addCriterion("sys_key_name not like", value, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameIn(List<String> values) {
            addCriterion("sys_key_name in", values, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameNotIn(List<String> values) {
            addCriterion("sys_key_name not in", values, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameBetween(String value1, String value2) {
            addCriterion("sys_key_name between", value1, value2, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyNameNotBetween(String value1, String value2) {
            addCriterion("sys_key_name not between", value1, value2, "sysKeyName");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueIsNull() {
            addCriterion("sys_key_value is null");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueIsNotNull() {
            addCriterion("sys_key_value is not null");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueEqualTo(String value) {
            addCriterion("sys_key_value =", value, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueNotEqualTo(String value) {
            addCriterion("sys_key_value <>", value, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueGreaterThan(String value) {
            addCriterion("sys_key_value >", value, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueGreaterThanOrEqualTo(String value) {
            addCriterion("sys_key_value >=", value, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueLessThan(String value) {
            addCriterion("sys_key_value <", value, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueLessThanOrEqualTo(String value) {
            addCriterion("sys_key_value <=", value, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueLike(String value) {
            addCriterion("sys_key_value like", value, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueNotLike(String value) {
            addCriterion("sys_key_value not like", value, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueIn(List<String> values) {
            addCriterion("sys_key_value in", values, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueNotIn(List<String> values) {
            addCriterion("sys_key_value not in", values, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueBetween(String value1, String value2) {
            addCriterion("sys_key_value between", value1, value2, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysKeyValueNotBetween(String value1, String value2) {
            addCriterion("sys_key_value not between", value1, value2, "sysKeyValue");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIsNull() {
            addCriterion("sys_add_time is null");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIsNotNull() {
            addCriterion("sys_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeEqualTo(Date value) {
            addCriterion("sys_add_time =", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotEqualTo(Date value) {
            addCriterion("sys_add_time <>", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeGreaterThan(Date value) {
            addCriterion("sys_add_time >", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_add_time >=", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeLessThan(Date value) {
            addCriterion("sys_add_time <", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("sys_add_time <=", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIn(List<Date> values) {
            addCriterion("sys_add_time in", values, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotIn(List<Date> values) {
            addCriterion("sys_add_time not in", values, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeBetween(Date value1, Date value2) {
            addCriterion("sys_add_time between", value1, value2, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("sys_add_time not between", value1, value2, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeIsNull() {
            addCriterion("sys_update_time is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeIsNotNull() {
            addCriterion("sys_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeEqualTo(Date value) {
            addCriterion("sys_update_time =", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeNotEqualTo(Date value) {
            addCriterion("sys_update_time <>", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeGreaterThan(Date value) {
            addCriterion("sys_update_time >", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_update_time >=", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeLessThan(Date value) {
            addCriterion("sys_update_time <", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("sys_update_time <=", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeIn(List<Date> values) {
            addCriterion("sys_update_time in", values, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeNotIn(List<Date> values) {
            addCriterion("sys_update_time not in", values, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("sys_update_time between", value1, value2, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("sys_update_time not between", value1, value2, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysDeletedIsNull() {
            addCriterion("sys_deleted is null");
            return (Criteria) this;
        }

        public Criteria andSysDeletedIsNotNull() {
            addCriterion("sys_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andSysDeletedEqualTo(Boolean value) {
            addCriterion("sys_deleted =", value, "sysDeleted");
            return (Criteria) this;
        }

        public Criteria andSysDeletedNotEqualTo(Boolean value) {
            addCriterion("sys_deleted <>", value, "sysDeleted");
            return (Criteria) this;
        }

        public Criteria andSysDeletedGreaterThan(Boolean value) {
            addCriterion("sys_deleted >", value, "sysDeleted");
            return (Criteria) this;
        }

        public Criteria andSysDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sys_deleted >=", value, "sysDeleted");
            return (Criteria) this;
        }

        public Criteria andSysDeletedLessThan(Boolean value) {
            addCriterion("sys_deleted <", value, "sysDeleted");
            return (Criteria) this;
        }

        public Criteria andSysDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("sys_deleted <=", value, "sysDeleted");
            return (Criteria) this;
        }

        public Criteria andSysDeletedIn(List<Boolean> values) {
            addCriterion("sys_deleted in", values, "sysDeleted");
            return (Criteria) this;
        }

        public Criteria andSysDeletedNotIn(List<Boolean> values) {
            addCriterion("sys_deleted not in", values, "sysDeleted");
            return (Criteria) this;
        }

        public Criteria andSysDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("sys_deleted between", value1, value2, "sysDeleted");
            return (Criteria) this;
        }

        public Criteria andSysDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sys_deleted not between", value1, value2, "sysDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_system
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_system
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}