package org.linlinjava.litemall.db.domain;

import java.util.Date;

public class TicUserFormid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_user_formid.for_id
     *
     * @mbggenerated
     */
    private Integer forId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_user_formid.for_formId
     *
     * @mbggenerated
     */
    private String forFormid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_user_formid.for_isprepay
     *
     * @mbggenerated
     */
    private Boolean forIsprepay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_user_formid.for_useAmount
     *
     * @mbggenerated
     */
    private Integer forUseamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_user_formid.for_expire_time
     *
     * @mbggenerated
     */
    private Date forExpireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_user_formid.for_openId
     *
     * @mbggenerated
     */
    private String forOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_user_formid.for_add_time
     *
     * @mbggenerated
     */
    private Date forAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_user_formid.for_update_time
     *
     * @mbggenerated
     */
    private Date forUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_user_formid.for_deleted
     *
     * @mbggenerated
     */
    private Boolean forDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_user_formid.for_id
     *
     * @return the value of tic_user_formid.for_id
     *
     * @mbggenerated
     */
    public Integer getForId() {
        return forId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_user_formid.for_id
     *
     * @param forId the value for tic_user_formid.for_id
     *
     * @mbggenerated
     */
    public void setForId(Integer forId) {
        this.forId = forId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_user_formid.for_formId
     *
     * @return the value of tic_user_formid.for_formId
     *
     * @mbggenerated
     */
    public String getForFormid() {
        return forFormid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_user_formid.for_formId
     *
     * @param forFormid the value for tic_user_formid.for_formId
     *
     * @mbggenerated
     */
    public void setForFormid(String forFormid) {
        this.forFormid = forFormid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_user_formid.for_isprepay
     *
     * @return the value of tic_user_formid.for_isprepay
     *
     * @mbggenerated
     */
    public Boolean getForIsprepay() {
        return forIsprepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_user_formid.for_isprepay
     *
     * @param forIsprepay the value for tic_user_formid.for_isprepay
     *
     * @mbggenerated
     */
    public void setForIsprepay(Boolean forIsprepay) {
        this.forIsprepay = forIsprepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_user_formid.for_useAmount
     *
     * @return the value of tic_user_formid.for_useAmount
     *
     * @mbggenerated
     */
    public Integer getForUseamount() {
        return forUseamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_user_formid.for_useAmount
     *
     * @param forUseamount the value for tic_user_formid.for_useAmount
     *
     * @mbggenerated
     */
    public void setForUseamount(Integer forUseamount) {
        this.forUseamount = forUseamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_user_formid.for_expire_time
     *
     * @return the value of tic_user_formid.for_expire_time
     *
     * @mbggenerated
     */
    public Date getForExpireTime() {
        return forExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_user_formid.for_expire_time
     *
     * @param forExpireTime the value for tic_user_formid.for_expire_time
     *
     * @mbggenerated
     */
    public void setForExpireTime(Date forExpireTime) {
        this.forExpireTime = forExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_user_formid.for_openId
     *
     * @return the value of tic_user_formid.for_openId
     *
     * @mbggenerated
     */
    public String getForOpenid() {
        return forOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_user_formid.for_openId
     *
     * @param forOpenid the value for tic_user_formid.for_openId
     *
     * @mbggenerated
     */
    public void setForOpenid(String forOpenid) {
        this.forOpenid = forOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_user_formid.for_add_time
     *
     * @return the value of tic_user_formid.for_add_time
     *
     * @mbggenerated
     */
    public Date getForAddTime() {
        return forAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_user_formid.for_add_time
     *
     * @param forAddTime the value for tic_user_formid.for_add_time
     *
     * @mbggenerated
     */
    public void setForAddTime(Date forAddTime) {
        this.forAddTime = forAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_user_formid.for_update_time
     *
     * @return the value of tic_user_formid.for_update_time
     *
     * @mbggenerated
     */
    public Date getForUpdateTime() {
        return forUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_user_formid.for_update_time
     *
     * @param forUpdateTime the value for tic_user_formid.for_update_time
     *
     * @mbggenerated
     */
    public void setForUpdateTime(Date forUpdateTime) {
        this.forUpdateTime = forUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_user_formid.for_deleted
     *
     * @return the value of tic_user_formid.for_deleted
     *
     * @mbggenerated
     */
    public Boolean getForDeleted() {
        return forDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_user_formid.for_deleted
     *
     * @param forDeleted the value for tic_user_formid.for_deleted
     *
     * @mbggenerated
     */
    public void setForDeleted(Boolean forDeleted) {
        this.forDeleted = forDeleted;
    }
}