package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TicViewpointExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public TicViewpointExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> viePicUrlCriteria;

        protected List<Criterion> vieVoiceUrlCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            viePicUrlCriteria = new ArrayList<Criterion>();
            vieVoiceUrlCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getViePicUrlCriteria() {
            return viePicUrlCriteria;
        }

        protected void addViePicUrlCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            viePicUrlCriteria.add(new Criterion(condition, value, "org.linlinjava.litemall.db.mybatis.JsonStringArrayTypeHandler"));
            allCriteria = null;
        }

        protected void addViePicUrlCriterion(String condition, String[] value1, String[] value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            viePicUrlCriteria.add(new Criterion(condition, value1, value2, "org.linlinjava.litemall.db.mybatis.JsonStringArrayTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getVieVoiceUrlCriteria() {
            return vieVoiceUrlCriteria;
        }

        protected void addVieVoiceUrlCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            vieVoiceUrlCriteria.add(new Criterion(condition, value, "org.linlinjava.litemall.db.mybatis.JsonStringArrayTypeHandler"));
            allCriteria = null;
        }

        protected void addVieVoiceUrlCriterion(String condition, String[] value1, String[] value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            vieVoiceUrlCriteria.add(new Criterion(condition, value1, value2, "org.linlinjava.litemall.db.mybatis.JsonStringArrayTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || viePicUrlCriteria.size() > 0
                || vieVoiceUrlCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(viePicUrlCriteria);
                allCriteria.addAll(vieVoiceUrlCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andVieIdIsNull() {
            addCriterion("vie_id is null");
            return (Criteria) this;
        }

        public Criteria andVieIdIsNotNull() {
            addCriterion("vie_id is not null");
            return (Criteria) this;
        }

        public Criteria andVieIdEqualTo(Integer value) {
            addCriterion("vie_id =", value, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieIdNotEqualTo(Integer value) {
            addCriterion("vie_id <>", value, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieIdGreaterThan(Integer value) {
            addCriterion("vie_id >", value, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vie_id >=", value, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieIdLessThan(Integer value) {
            addCriterion("vie_id <", value, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieIdLessThanOrEqualTo(Integer value) {
            addCriterion("vie_id <=", value, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieIdIn(List<Integer> values) {
            addCriterion("vie_id in", values, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieIdNotIn(List<Integer> values) {
            addCriterion("vie_id not in", values, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieIdBetween(Integer value1, Integer value2) {
            addCriterion("vie_id between", value1, value2, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vie_id not between", value1, value2, "vieId");
            return (Criteria) this;
        }

        public Criteria andVieTitleIsNull() {
            addCriterion("vie_title is null");
            return (Criteria) this;
        }

        public Criteria andVieTitleIsNotNull() {
            addCriterion("vie_title is not null");
            return (Criteria) this;
        }

        public Criteria andVieTitleEqualTo(String value) {
            addCriterion("vie_title =", value, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleNotEqualTo(String value) {
            addCriterion("vie_title <>", value, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleGreaterThan(String value) {
            addCriterion("vie_title >", value, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleGreaterThanOrEqualTo(String value) {
            addCriterion("vie_title >=", value, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleLessThan(String value) {
            addCriterion("vie_title <", value, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleLessThanOrEqualTo(String value) {
            addCriterion("vie_title <=", value, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleLike(String value) {
            addCriterion("vie_title like", value, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleNotLike(String value) {
            addCriterion("vie_title not like", value, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleIn(List<String> values) {
            addCriterion("vie_title in", values, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleNotIn(List<String> values) {
            addCriterion("vie_title not in", values, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleBetween(String value1, String value2) {
            addCriterion("vie_title between", value1, value2, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieTitleNotBetween(String value1, String value2) {
            addCriterion("vie_title not between", value1, value2, "vieTitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleIsNull() {
            addCriterion("vie_subtitle is null");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleIsNotNull() {
            addCriterion("vie_subtitle is not null");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleEqualTo(String value) {
            addCriterion("vie_subtitle =", value, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleNotEqualTo(String value) {
            addCriterion("vie_subtitle <>", value, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleGreaterThan(String value) {
            addCriterion("vie_subtitle >", value, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleGreaterThanOrEqualTo(String value) {
            addCriterion("vie_subtitle >=", value, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleLessThan(String value) {
            addCriterion("vie_subtitle <", value, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleLessThanOrEqualTo(String value) {
            addCriterion("vie_subtitle <=", value, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleLike(String value) {
            addCriterion("vie_subtitle like", value, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleNotLike(String value) {
            addCriterion("vie_subtitle not like", value, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleIn(List<String> values) {
            addCriterion("vie_subtitle in", values, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleNotIn(List<String> values) {
            addCriterion("vie_subtitle not in", values, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleBetween(String value1, String value2) {
            addCriterion("vie_subtitle between", value1, value2, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieSubtitleNotBetween(String value1, String value2) {
            addCriterion("vie_subtitle not between", value1, value2, "vieSubtitle");
            return (Criteria) this;
        }

        public Criteria andVieReadIsNull() {
            addCriterion("vie_read is null");
            return (Criteria) this;
        }

        public Criteria andVieReadIsNotNull() {
            addCriterion("vie_read is not null");
            return (Criteria) this;
        }

        public Criteria andVieReadEqualTo(String value) {
            addCriterion("vie_read =", value, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadNotEqualTo(String value) {
            addCriterion("vie_read <>", value, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadGreaterThan(String value) {
            addCriterion("vie_read >", value, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadGreaterThanOrEqualTo(String value) {
            addCriterion("vie_read >=", value, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadLessThan(String value) {
            addCriterion("vie_read <", value, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadLessThanOrEqualTo(String value) {
            addCriterion("vie_read <=", value, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadLike(String value) {
            addCriterion("vie_read like", value, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadNotLike(String value) {
            addCriterion("vie_read not like", value, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadIn(List<String> values) {
            addCriterion("vie_read in", values, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadNotIn(List<String> values) {
            addCriterion("vie_read not in", values, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadBetween(String value1, String value2) {
            addCriterion("vie_read between", value1, value2, "vieRead");
            return (Criteria) this;
        }

        public Criteria andVieReadNotBetween(String value1, String value2) {
            addCriterion("vie_read not between", value1, value2, "vieRead");
            return (Criteria) this;
        }

        public Criteria andViePicUrlIsNull() {
            addCriterion("vie_pic_url is null");
            return (Criteria) this;
        }

        public Criteria andViePicUrlIsNotNull() {
            addCriterion("vie_pic_url is not null");
            return (Criteria) this;
        }

        public Criteria andViePicUrlEqualTo(String[] value) {
            addViePicUrlCriterion("vie_pic_url =", value, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlNotEqualTo(String[] value) {
            addViePicUrlCriterion("vie_pic_url <>", value, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlGreaterThan(String[] value) {
            addViePicUrlCriterion("vie_pic_url >", value, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlGreaterThanOrEqualTo(String[] value) {
            addViePicUrlCriterion("vie_pic_url >=", value, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlLessThan(String[] value) {
            addViePicUrlCriterion("vie_pic_url <", value, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlLessThanOrEqualTo(String[] value) {
            addViePicUrlCriterion("vie_pic_url <=", value, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlLike(String[] value) {
            addViePicUrlCriterion("vie_pic_url like", value, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlNotLike(String[] value) {
            addViePicUrlCriterion("vie_pic_url not like", value, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlIn(List<String[]> values) {
            addViePicUrlCriterion("vie_pic_url in", values, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlNotIn(List<String[]> values) {
            addViePicUrlCriterion("vie_pic_url not in", values, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlBetween(String[] value1, String[] value2) {
            addViePicUrlCriterion("vie_pic_url between", value1, value2, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andViePicUrlNotBetween(String[] value1, String[] value2) {
            addViePicUrlCriterion("vie_pic_url not between", value1, value2, "viePicUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlIsNull() {
            addCriterion("vie_voice_url is null");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlIsNotNull() {
            addCriterion("vie_voice_url is not null");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlEqualTo(String[] value) {
            addVieVoiceUrlCriterion("vie_voice_url =", value, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlNotEqualTo(String[] value) {
            addVieVoiceUrlCriterion("vie_voice_url <>", value, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlGreaterThan(String[] value) {
            addVieVoiceUrlCriterion("vie_voice_url >", value, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlGreaterThanOrEqualTo(String[] value) {
            addVieVoiceUrlCriterion("vie_voice_url >=", value, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlLessThan(String[] value) {
            addVieVoiceUrlCriterion("vie_voice_url <", value, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlLessThanOrEqualTo(String[] value) {
            addVieVoiceUrlCriterion("vie_voice_url <=", value, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlLike(String[] value) {
            addVieVoiceUrlCriterion("vie_voice_url like", value, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlNotLike(String[] value) {
            addVieVoiceUrlCriterion("vie_voice_url not like", value, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlIn(List<String[]> values) {
            addVieVoiceUrlCriterion("vie_voice_url in", values, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlNotIn(List<String[]> values) {
            addVieVoiceUrlCriterion("vie_voice_url not in", values, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlBetween(String[] value1, String[] value2) {
            addVieVoiceUrlCriterion("vie_voice_url between", value1, value2, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieVoiceUrlNotBetween(String[] value1, String[] value2) {
            addVieVoiceUrlCriterion("vie_voice_url not between", value1, value2, "vieVoiceUrl");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderIsNull() {
            addCriterion("vie_sort_order is null");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderIsNotNull() {
            addCriterion("vie_sort_order is not null");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderEqualTo(Integer value) {
            addCriterion("vie_sort_order =", value, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderNotEqualTo(Integer value) {
            addCriterion("vie_sort_order <>", value, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderGreaterThan(Integer value) {
            addCriterion("vie_sort_order >", value, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("vie_sort_order >=", value, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderLessThan(Integer value) {
            addCriterion("vie_sort_order <", value, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderLessThanOrEqualTo(Integer value) {
            addCriterion("vie_sort_order <=", value, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderIn(List<Integer> values) {
            addCriterion("vie_sort_order in", values, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderNotIn(List<Integer> values) {
            addCriterion("vie_sort_order not in", values, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderBetween(Integer value1, Integer value2) {
            addCriterion("vie_sort_order between", value1, value2, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieSortOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("vie_sort_order not between", value1, value2, "vieSortOrder");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeIsNull() {
            addCriterion("vie_add_time is null");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeIsNotNull() {
            addCriterion("vie_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeEqualTo(Date value) {
            addCriterion("vie_add_time =", value, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeNotEqualTo(Date value) {
            addCriterion("vie_add_time <>", value, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeGreaterThan(Date value) {
            addCriterion("vie_add_time >", value, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("vie_add_time >=", value, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeLessThan(Date value) {
            addCriterion("vie_add_time <", value, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("vie_add_time <=", value, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeIn(List<Date> values) {
            addCriterion("vie_add_time in", values, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeNotIn(List<Date> values) {
            addCriterion("vie_add_time not in", values, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeBetween(Date value1, Date value2) {
            addCriterion("vie_add_time between", value1, value2, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("vie_add_time not between", value1, value2, "vieAddTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeIsNull() {
            addCriterion("vie_update_time is null");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeIsNotNull() {
            addCriterion("vie_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeEqualTo(Date value) {
            addCriterion("vie_update_time =", value, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeNotEqualTo(Date value) {
            addCriterion("vie_update_time <>", value, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeGreaterThan(Date value) {
            addCriterion("vie_update_time >", value, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("vie_update_time >=", value, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeLessThan(Date value) {
            addCriterion("vie_update_time <", value, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("vie_update_time <=", value, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeIn(List<Date> values) {
            addCriterion("vie_update_time in", values, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeNotIn(List<Date> values) {
            addCriterion("vie_update_time not in", values, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("vie_update_time between", value1, value2, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("vie_update_time not between", value1, value2, "vieUpdateTime");
            return (Criteria) this;
        }

        public Criteria andVieDeletedIsNull() {
            addCriterion("vie_deleted is null");
            return (Criteria) this;
        }

        public Criteria andVieDeletedIsNotNull() {
            addCriterion("vie_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andVieDeletedEqualTo(Boolean value) {
            addCriterion("vie_deleted =", value, "vieDeleted");
            return (Criteria) this;
        }

        public Criteria andVieDeletedNotEqualTo(Boolean value) {
            addCriterion("vie_deleted <>", value, "vieDeleted");
            return (Criteria) this;
        }

        public Criteria andVieDeletedGreaterThan(Boolean value) {
            addCriterion("vie_deleted >", value, "vieDeleted");
            return (Criteria) this;
        }

        public Criteria andVieDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("vie_deleted >=", value, "vieDeleted");
            return (Criteria) this;
        }

        public Criteria andVieDeletedLessThan(Boolean value) {
            addCriterion("vie_deleted <", value, "vieDeleted");
            return (Criteria) this;
        }

        public Criteria andVieDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("vie_deleted <=", value, "vieDeleted");
            return (Criteria) this;
        }

        public Criteria andVieDeletedIn(List<Boolean> values) {
            addCriterion("vie_deleted in", values, "vieDeleted");
            return (Criteria) this;
        }

        public Criteria andVieDeletedNotIn(List<Boolean> values) {
            addCriterion("vie_deleted not in", values, "vieDeleted");
            return (Criteria) this;
        }

        public Criteria andVieDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("vie_deleted between", value1, value2, "vieDeleted");
            return (Criteria) this;
        }

        public Criteria andVieDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("vie_deleted not between", value1, value2, "vieDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_viewpoint
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tic_viewpoint
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}