package org.linlinjava.litemall.db.domain;

import java.util.Arrays;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONType;
import com.fasterxml.jackson.annotation.JsonFormat;

public class TicViewpoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_id
     *
     * @mbggenerated
     */
    private Integer vieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_title
     *
     * @mbggenerated
     */
    private String vieTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_subtitle
     *
     * @mbggenerated
     */
    private String vieSubtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_read
     *
     * @mbggenerated
     */
    private String vieRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_pic_url
     *
     * @mbggenerated
     */
    private String[] viePicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_voice_url
     *
     * @mbggenerated
     */
    private String[] vieVoiceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_sort_order
     *
     * @mbggenerated
     */
    private Integer vieSortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_add_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date vieAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_update_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date vieUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_deleted
     *
     * @mbggenerated
     */
    private Boolean vieDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tic_viewpoint.vie_content
     *
     * @mbggenerated
     */
    private String vieContent;

    private Integer vieGateId;


    public Integer getVieGateId() {
        return vieGateId;
    }

    public void setVieGateId(Integer vieGateId) {
        this.vieGateId = vieGateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_id
     *
     * @return the value of tic_viewpoint.vie_id
     *
     * @mbggenerated
     */
    public Integer getVieId() {
        return vieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_id
     *
     * @param vieId the value for tic_viewpoint.vie_id
     *
     * @mbggenerated
     */
    public void setVieId(Integer vieId) {
        this.vieId = vieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_title
     *
     * @return the value of tic_viewpoint.vie_title
     *
     * @mbggenerated
     */
    public String getVieTitle() {
        return vieTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_title
     *
     * @param vieTitle the value for tic_viewpoint.vie_title
     *
     * @mbggenerated
     */
    public void setVieTitle(String vieTitle) {
        this.vieTitle = vieTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_subtitle
     *
     * @return the value of tic_viewpoint.vie_subtitle
     *
     * @mbggenerated
     */
    public String getVieSubtitle() {
        return vieSubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_subtitle
     *
     * @param vieSubtitle the value for tic_viewpoint.vie_subtitle
     *
     * @mbggenerated
     */
    public void setVieSubtitle(String vieSubtitle) {
        this.vieSubtitle = vieSubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_read
     *
     * @return the value of tic_viewpoint.vie_read
     *
     * @mbggenerated
     */
    public String getVieRead() {
        return vieRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_read
     *
     * @param vieRead the value for tic_viewpoint.vie_read
     *
     * @mbggenerated
     */
    public void setVieRead(String vieRead) {
        this.vieRead = vieRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_pic_url
     *
     * @return the value of tic_viewpoint.vie_pic_url
     *
     * @mbggenerated
     */
    public String[] getViePicUrl() {
        return viePicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_pic_url
     *
     * @param viePicUrl the value for tic_viewpoint.vie_pic_url
     *
     * @mbggenerated
     */
    public void setViePicUrl(String[] viePicUrl) {
        this.viePicUrl = viePicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_voice_url
     *
     * @return the value of tic_viewpoint.vie_voice_url
     *
     * @mbggenerated
     */
    public String[] getVieVoiceUrl() {
        return vieVoiceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_voice_url
     *
     * @param vieVoiceUrl the value for tic_viewpoint.vie_voice_url
     *
     * @mbggenerated
     */
    public void setVieVoiceUrl(String[] vieVoiceUrl) {
        this.vieVoiceUrl = vieVoiceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_sort_order
     *
     * @return the value of tic_viewpoint.vie_sort_order
     *
     * @mbggenerated
     */
    public Integer getVieSortOrder() {
        return vieSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_sort_order
     *
     * @param vieSortOrder the value for tic_viewpoint.vie_sort_order
     *
     * @mbggenerated
     */
    public void setVieSortOrder(Integer vieSortOrder) {
        this.vieSortOrder = vieSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_add_time
     *
     * @return the value of tic_viewpoint.vie_add_time
     *
     * @mbggenerated
     */
    public Date getVieAddTime() {
        return vieAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_add_time
     *
     * @param vieAddTime the value for tic_viewpoint.vie_add_time
     *
     * @mbggenerated
     */
    public void setVieAddTime(Date vieAddTime) {
        this.vieAddTime = vieAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_update_time
     *
     * @return the value of tic_viewpoint.vie_update_time
     *
     * @mbggenerated
     */
    public Date getVieUpdateTime() {
        return vieUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_update_time
     *
     * @param vieUpdateTime the value for tic_viewpoint.vie_update_time
     *
     * @mbggenerated
     */
    public void setVieUpdateTime(Date vieUpdateTime) {
        this.vieUpdateTime = vieUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_deleted
     *
     * @return the value of tic_viewpoint.vie_deleted
     *
     * @mbggenerated
     */
    public Boolean getVieDeleted() {
        return vieDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_deleted
     *
     * @param vieDeleted the value for tic_viewpoint.vie_deleted
     *
     * @mbggenerated
     */
    public void setVieDeleted(Boolean vieDeleted) {
        this.vieDeleted = vieDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tic_viewpoint.vie_content
     *
     * @return the value of tic_viewpoint.vie_content
     *
     * @mbggenerated
     */
    public String getVieContent() {
        return vieContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tic_viewpoint.vie_content
     *
     * @param vieContent the value for tic_viewpoint.vie_content
     *
     * @mbggenerated
     */
    public void setVieContent(String vieContent) {
        this.vieContent = vieContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vieId=").append(vieId);
        sb.append(", vieTitle=").append(vieTitle);
        sb.append(", vieSubtitle=").append(vieSubtitle);
        sb.append(", vieRead=").append(vieRead);
        sb.append(", viePicUrl=").append(viePicUrl);
        sb.append(", vieVoiceUrl=").append(vieVoiceUrl);
        sb.append(", vieSortOrder=").append(vieSortOrder);
        sb.append(", vieAddTime=").append(vieAddTime);
        sb.append(", vieUpdateTime=").append(vieUpdateTime);
        sb.append(", vieDeleted=").append(vieDeleted);
        sb.append(", vieContent=").append(vieContent);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TicViewpoint other = (TicViewpoint) that;
        return (this.getVieId() == null ? other.getVieId() == null : this.getVieId().equals(other.getVieId()))
            && (this.getVieTitle() == null ? other.getVieTitle() == null : this.getVieTitle().equals(other.getVieTitle()))
            && (this.getVieSubtitle() == null ? other.getVieSubtitle() == null : this.getVieSubtitle().equals(other.getVieSubtitle()))
            && (this.getVieRead() == null ? other.getVieRead() == null : this.getVieRead().equals(other.getVieRead()))
            && (Arrays.equals(this.getViePicUrl(), other.getViePicUrl()))
            && (Arrays.equals(this.getVieVoiceUrl(), other.getVieVoiceUrl()))
            && (this.getVieSortOrder() == null ? other.getVieSortOrder() == null : this.getVieSortOrder().equals(other.getVieSortOrder()))
            && (this.getVieAddTime() == null ? other.getVieAddTime() == null : this.getVieAddTime().equals(other.getVieAddTime()))
            && (this.getVieUpdateTime() == null ? other.getVieUpdateTime() == null : this.getVieUpdateTime().equals(other.getVieUpdateTime()))
            && (this.getVieDeleted() == null ? other.getVieDeleted() == null : this.getVieDeleted().equals(other.getVieDeleted()))
            && (this.getVieContent() == null ? other.getVieContent() == null : this.getVieContent().equals(other.getVieContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tic_viewpoint
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVieId() == null) ? 0 : getVieId().hashCode());
        result = prime * result + ((getVieTitle() == null) ? 0 : getVieTitle().hashCode());
        result = prime * result + ((getVieSubtitle() == null) ? 0 : getVieSubtitle().hashCode());
        result = prime * result + ((getVieRead() == null) ? 0 : getVieRead().hashCode());
        result = prime * result + (Arrays.hashCode(getViePicUrl()));
        result = prime * result + (Arrays.hashCode(getVieVoiceUrl()));
        result = prime * result + ((getVieSortOrder() == null) ? 0 : getVieSortOrder().hashCode());
        result = prime * result + ((getVieAddTime() == null) ? 0 : getVieAddTime().hashCode());
        result = prime * result + ((getVieUpdateTime() == null) ? 0 : getVieUpdateTime().hashCode());
        result = prime * result + ((getVieDeleted() == null) ? 0 : getVieDeleted().hashCode());
        result = prime * result + ((getVieContent() == null) ? 0 : getVieContent().hashCode());
        return result;
    }
}