spring:
  profiles:
    active: @profileActive@, db, core, admin, wx
  messages:
    encoding: UTF-8
  jmx:
    default-domain: ticket

server:
  port: 8013

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  ERROR
    org.linlinjava.litemall.db:  ERROR
    org.linlinjava.litemall.admin:  ERROR
    org.linlinjava.litemall.wx:  ERROR
    org.linlinjava.litemall:  ERROR